#!/bin/sh
# Generate the cmd OSR front-end: portsh-cmd.cmd + _warm.cmd + _warmp.cmd. This replaces the old
# :ev + record/replay handoff with the substrate-unification model -- ONE engine (the resumable
# interpreter) starts the program and OSR-flips to compiled code as it becomes available. No re-run,
# no effect log, every effect happens exactly once, live:
#
#   tooling cold (first run of this build)  -> extract comp-cmd to the build cache, FOREGROUND, once.
#   program cold (no compiled artifacts)    -> interp-cmd runs the program INTERPRETED while a
#                                              BACKGROUND warmer (_warmp.cmd) compiles it into the
#                                              program cache; the publish is ATOMIC (tmp dir -> move),
#                                              so the RUNNING interp flips per-fn at the next call
#                                              boundary once artifacts land (eld_route's PORTSH_OSRDIR
#                                              check). Next runs skip compilation entirely.
#   program warm                            -> same interp-cmd run; every fn flips to its compiled
#                                              artifact at FIRST call. Strictly faster than the old
#                                              warm path (load-cmd), which recompiled the program on
#                                              every invocation.
#
# The program cache is keyed by CONTENT hash (certutil SHA256) -- editing the program invalidates it.
# The REPL (no file arg) is always the interpreter (the decided cmd-REPL engine).
set -eu
cd "$(dirname "$0")"
[ -f comp-cmd/interp-cmd.cmd ] || sh build-interp-cmd.sh >/dev/null
# repack if the self-extractor is missing OR older than the comp-cmd payload (interp-cmd.cmd is in it)
if [ ! -f comp-cmd.selfx.cmd ] || [ comp-cmd/interp-cmd.cmd -nt comp-cmd.selfx.cmd ]; then
  sh tools/pack-comp-cmd.sh >/dev/null
fi
BUILD=$(sed -n 's/^set "PORTSH_BUILD=\([0-9a-f][0-9a-f]*\)".*/\1/p' comp-cmd.selfx.cmd | head -1)
[ -n "$BUILD" ] || { echo "could not read build id from comp-cmd.selfx.cmd"; exit 1; }

# _warm.cmd -- tooling extractor: self-extract comp-cmd into a temp dir, atomic-rename to the build
# cache, drop the .ok marker. %1 = final cache dir. (Same as the old warmer; now run FOREGROUND once.)
{ printf '@echo off\r\n'
  printf 'rem GENERATED by build-portsh-cmd.sh -- tooling extractor (self-extract -> cache -> .ok)\r\n'
  printf 'set "C=%%~1"\r\n'
  printf 'set "E=%%C%%.tmp"\r\n'
  printf 'if exist "%%E%%" rmdir /s /q "%%E%%"\r\n'
  printf 'call "%%~dp0comp-cmd.selfx.cmd" "%%E%%" >nul 2>&1\r\n'
  printf 'move "%%E%%" "%%C%%" >nul 2>&1\r\n'
  printf 'break>"%%C%%\\.ok"\r\n'
} > _warm.cmd

# _warmp.cmd -- the background PROGRAM warmer: compile %2 into %3 (atomic: %3.tmp -> move -> .ok),
# using interp-cmd's compile-only mode (PORTSH_OSRCOMPILE) so the partition path -- and therefore
# every fn label and __lamN/__evN number -- is IDENTICAL to what the foreground interp registered.
{ printf '@echo off\r\n'
  printf 'rem GENERATED by build-portsh-cmd.sh -- background program warmer (compile -> cache -> .ok)\r\n'
  printf 'set "C=%%~1"\r\n'
  printf 'set "P=%%~2"\r\n'
  printf 'set "D=%%~3"\r\n'
  printf 'set "PATH=%%C%%;%%PATH%%"\r\n'
  printf 'if exist "%%D%%.tmp" rmdir /s /q "%%D%%.tmp"\r\n'
  printf 'mkdir "%%D%%.tmp"\r\n'
  printf 'set "PORTSH_OSRCOMPILE=%%D%%.tmp"\r\n'
  printf 'cmd /c "call interp-cmd.cmd "%%P%%"" >nul 2>&1\r\n'
  printf 'rem promote ONLY a successful compile (a failed/killed one must not publish an empty cache,\r\n'
  printf 'rem which would poison every future warm run); clear a stale dest or `move` NESTS into it.\r\n'
  printf 'if errorlevel 1 exit /b 1\r\n'
  printf 'set "PORTSH_OSRCOMPILE="\r\n'
  printf 'if exist "%%D%%" rmdir /s /q "%%D%%"\r\n'
  printf 'move "%%D%%.tmp" "%%D%%" >nul 2>&1\r\n'
  printf 'break>"%%D%%\\.ok"\r\n'
} > _warmp.cmd

# portsh-cmd.cmd -- the front-end.
{ printf '@echo off\r\n'
  printf 'rem GENERATED by build-portsh-cmd.sh -- portsh cmd OSR front-end (build %s)\r\n' "$BUILD"
  printf 'setlocal enabledelayedexpansion\r\n'
  printf 'set "HERE=%%~dp0"\r\n'
  printf 'set "CACHE=%%LOCALAPPDATA%%\\portsh\\%s"\r\n' "$BUILD"
  printf 'rem tooling: extract once per build (foreground; first-ever run of this build only)\r\n'
  printf 'if not exist "%%CACHE%%\\.ok" call "%%HERE%%_warm.cmd" "%%CACHE%%"\r\n'
  printf 'set "PATH=%%CACHE%%;%%PATH%%"\r\n'
  printf 'if "%%~1"=="" goto repl\r\n'
  printf 'set "PROG=%%~f1"\r\n'
  printf 'rem program cache key = content hash (an edited program recompiles; identical content reuses)\r\n'
  printf 'set "H="\r\n'
  printf 'for /f "skip=1 tokens=1" %%%%h in ('"'"'certutil -hashfile "!PROG!" SHA256'"'"') do if not defined H set "H=%%%%h"\r\n'
  printf 'set "PCACHE=%%CACHE%%\\p\\!H:~0,16!"\r\n'
  printf 'if not exist "%%CACHE%%\\p" mkdir "%%CACHE%%\\p"\r\n'
  printf 'rem cold program: compile it in the BACKGROUND; the foreground interp flips when it lands\r\n'
  printf 'rem the extra outer quotes defeat cmd /c quote-stripping (else the multi-quoted call mangles\r\n'
  printf 'rem and the warmer dies instantly, publishing an empty cache)\r\n'
  printf 'if not exist "!PCACHE!\\.ok" start "" /b cmd /c ""%%HERE%%_warmp.cmd" "%%CACHE%%" "!PROG!" "!PCACHE!""\r\n'
  printf 'set "PORTSH_OSRDIR=!PCACHE!"\r\n'
  printf 'set "PORTSH_SCRIPT=1"\r\n'
  printf 'cmd /c "call interp-cmd.cmd "!PROG!""\r\n'
  printf 'endlocal\r\n'
  printf 'goto :eof\r\n'
  printf ':repl\r\n'
  printf 'rem the REPL is always the interpreter (cmd JIT compile is too slow per input)\r\n'
  printf 'call interp-cmd.cmd\r\n'
  printf 'endlocal\r\n'
  printf 'goto :eof\r\n'
} > portsh-cmd.cmd

echo "built portsh-cmd.cmd + _warm.cmd + _warmp.cmd (build $BUILD)"
