#!/bin/sh
# Weave the SHIPPING polyglot `portsh.cmd` -- ONE file, valid as both POSIX sh and Windows batch,
# running the REAL engines (#31):
#   sh  half: the unified always-JIT loader (load-sh.sh) -- file arg = compile+run; no arg = JIT REPL.
#   cmd half: the OSR front-end -- tooling cold = self-extract (the comp-cmd tree is EMBEDDED as a
#             pure-cmd self-extractor section, dispatched via `portsh.cmd __extract DIR`) once per
#             build; program cold = interp + background warmer + flip-as-artifacts-land; warm = all
#             fns flip at first call; no arg = the warming interp REPL.

#
# Dual-validity (same trick as build.sh): the file is CRLF throughout (cmd needs CR for labels); sh
# line 1 re-execs a CR-stripped copy of itself; cmd sees lines 1-2 as ':' labels and `goto`s over the
# entire sh half; sh `exit`s before reaching the batch half, so the megabyte of `echo(` payload lines
# is never parsed by sh.
set -eu
cd "$(dirname "$0")"
[ -f load-sh.sh ] || sh build-load-sh.sh >/dev/null
[ -f comp-cmd/interp-cmd.cmd ] || sh build-interp-cmd.sh >/dev/null
if [ ! -f comp-cmd.selfx.cmd ] || [ comp-cmd/interp-cmd.cmd -nt comp-cmd.selfx.cmd ]; then
  sh tools/pack-comp-cmd.sh >/dev/null
fi
BUILD=$(sed -n 's/^set "PORTSH_BUILD=\([0-9a-f][0-9a-f]*\)".*/\1/p' comp-cmd.selfx.cmd | head -1)
[ -n "$BUILD" ] || { echo "could not read build id from comp-cmd.selfx.cmd"; exit 1; }

python3 - load-sh.sh comp-cmd.selfx.cmd portsh.cmd "$BUILD" <<'PY'
import sys
loadsh, selfx, out, build = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]

# NOTE: the re-exec cooks to a TEMP FILE (not a pipe like build.sh's vau weave) -- a pipe would make
# the inner sh's stdin the script itself, so an interactive REPL (`read` from the user) would consume
# the file's own text. A temp file passes the real stdin through.
hdr = (
  ''':;[ -n "${PORTSH_COOKED-}" ]||{ t=$(mktemp);tr -d '\\r'<"$0">"$t";PORTSH_COOKED=1 PORTSH_SELF="$0" sh "$t" "$@";r=$?;rm -f "$t";exit $r; } #\n'''
  ''':<<'::CMDLITERAL'\n'''
  '''@echo off\n'''
  '''goto :CMDSTART\n'''
  '''::CMDLITERAL\n'''
)

sh_half = open(loadsh, 'rb').read().decode('latin-1')

# the embedded self-extractor: take the selfx body from its `setlocal disableDelayedExpansion` line on,
# rebinding PSDIR to %~2 (the __extract dispatch passes the dest as arg 2). Drop its usage check.
sx = open(selfx, 'rb').read().decode('latin-1').replace('\r\n', '\n')
sx_lines = sx.split('\n')
start = next(i for i, l in enumerate(sx_lines) if l.startswith('setlocal disableDelayedExpansion'))
body = []
for l in sx_lines[start:]:
    if l.startswith('set "PSDIR=%~1"'):
        body.append('set "PSDIR=%~2"')
    elif l.startswith('if "%PSDIR%"=="" '):
        continue
    else:
        body.append(l)
sx_body = '\n'.join(body).rstrip('\n')

cmd_half = '''@echo off
rem ============ portsh cmd OSR front-end (build {B}) -- generated by build-polyglot.sh ============
if "%~1"=="__extract" goto :PSELFX
setlocal enabledelayedexpansion
set "CACHE=%LOCALAPPDATA%\\portsh\\{B}"
if exist "%CACHE%\\.ok" goto pcache_ok
rem tooling cold: self-extract the embedded comp-cmd tree, once per build (atomic: tmp -> move -> .ok)
if exist "%CACHE%.tmp" rmdir /s /q "%CACHE%.tmp"
cmd /c call "%~f0" __extract "%CACHE%.tmp" >nul 2>&1
move "%CACHE%.tmp" "%CACHE%" >nul 2>&1
break>"%CACHE%\\.ok"
:pcache_ok
set "PATH=%CACHE%;%PATH%"
if "%~1"=="" goto prepl
set "PROG=%~f1"
rem program cache key = content hash (edits invalidate; identical content reuses)
set "H="
for /f "skip=1 tokens=1" %%h in ('certutil -hashfile "!PROG!" SHA256') do if not defined H set "H=%%h"
set "PCACHE=%CACHE%\\p\\!H:~0,16!"
if not exist "%CACHE%\\p" mkdir "%CACHE%\\p"
if exist "!PCACHE!\\.ok" goto prun
rem program cold: generate the background warmer to %TEMP% (per-program, all paths CONCRETE -- no args,
rem so the schtasks action string needs no nested quoting) and launch it DETACHED via the Task Scheduler:
rem a `start /b` child lives in this console/ssh job and DIES when the session ends (compiling a program
rem takes minutes -- longer than many runs), silently leaving the cache forever cold. A scheduled task
rem runs outside the job and always finishes. Fallback to start /b if schtasks is unavailable.
set "WARMP=%TEMP%\\portsh_warmp_!H:~0,16!.cmd"
> "!WARMP!" echo @echo off
>>"!WARMP!" echo set "PATH=%CACHE%;%%PATH%%"
>>"!WARMP!" echo if exist "!PCACHE!.tmp" rmdir /s /q "!PCACHE!.tmp"
>>"!WARMP!" echo mkdir "!PCACHE!.tmp"
>>"!WARMP!" echo set "PORTSH_OSRCOMPILE=!PCACHE!.tmp"
>>"!WARMP!" echo cmd /c "call interp-cmd.cmd "!PROG!"" ^>nul 2^>^&1
>>"!WARMP!" echo if errorlevel 1 goto wpend
>>"!WARMP!" echo set "PORTSH_OSRCOMPILE="
>>"!WARMP!" echo if exist "!PCACHE!" rmdir /s /q "!PCACHE!"
>>"!WARMP!" echo move "!PCACHE!.tmp" "!PCACHE!" ^>nul 2^>^&1
>>"!WARMP!" echo break^>"!PCACHE!\\.ok"
>>"!WARMP!" echo :wpend
>>"!WARMP!" echo schtasks /delete /f /tn "portsh_w_!H:~0,16!" ^>nul 2^>^&1
set "WOK="
schtasks /create /f /tn "portsh_w_!H:~0,16!" /tr "'!WARMP!'" /sc once /st 00:00 >nul 2>&1 && set "WOK=1"
if defined WOK (schtasks /run /tn "portsh_w_!H:~0,16!" >nul 2>&1) else (start "" /b cmd /c ""!WARMP!"" >nul 2>&1)
:prun
set "PORTSH_OSRDIR=!PCACHE!"
set "PORTSH_SCRIPT=1"
cmd /c "call interp-cmd.cmd "!PROG!""
endlocal
goto :eof
:prepl
rem the REPL is the warming interpreter (per-input background compile + flip)
call interp-cmd.cmd
endlocal
goto :eof
:PSELFX
{SX}
exit /b 0
'''.replace('{B}', build).replace('{SX}', sx_body)

whole = hdr + sh_half.rstrip('\n') + '\nexit $?\n:CMDSTART\n' + cmd_half
whole = whole.replace('\r\n', '\n').replace('\n', '\r\n')
open(out, 'wb').write(whole.encode('latin-1'))
PY
echo "built portsh.cmd ($(wc -c < portsh.cmd) bytes, build $BUILD)"
