#!/bin/sh
# Generate the cmd two-tier FRONT-END driver: portsh-cmd.cmd + _warm.cmd. This is the integration of
# the self-extractor (#30) and record-replay (#33/#34) into the real first-run UX:
#   warm (cache .ok exists)  -> run the cmd JIT directly from the cache
#   cold (no .ok)            -> EXTRACT comp-cmd to the cache in the BACKGROUND (the JIT "warming")
#                               while :ev runs in the FOREGROUND in LOG mode (the latency curtain) and
#                               abandons (exit 42) the moment .ok appears; then the JIT REPLAYS the
#                               logged prefix and goes LIVE. :ev exit 0 = finished before warm (done);
#                               a crash (deep-recursion overflow) = also hand off to the JIT.
# The build id keys the per-build cache (so a new build re-extracts). The shipping polyglot folds this
# into portsh.cmd's cmd half; this standalone form lets us test the handoff on the VM.
set -eu
cd "$(dirname "$0")"
[ -f comp-cmd.selfx.cmd ] || sh tools/pack-comp-cmd.sh >/dev/null
BUILD=$(sed -n 's/^set "PORTSH_BUILD=\([0-9a-f][0-9a-f]*\)".*/\1/p' comp-cmd.selfx.cmd | head -1)
[ -n "$BUILD" ] || { echo "could not read build id from comp-cmd.selfx.cmd"; exit 1; }

# _warm.cmd -- the background warmer: self-extract comp-cmd into a temp dir, atomic-rename to the
# cache, then drop the .ok marker (the warm signal :ev polls). %1 = final cache dir.
{ printf '@echo off\r\n'
  printf 'rem GENERATED by build-portsh-cmd.sh -- background JIT warmer (self-extract -> cache -> .ok)\r\n'
  printf 'set "C=%%~1"\r\n'
  printf 'set "E=%%C%%.tmp"\r\n'
  printf 'if exist "%%E%%" rmdir /s /q "%%E%%"\r\n'
  printf 'call "%%~dp0comp-cmd.selfx.cmd" "%%E%%" >nul 2>&1\r\n'
  printf 'move "%%E%%" "%%C%%" >nul 2>&1\r\n'
  printf 'break>"%%C%%\\.ok"\r\n'
} > _warm.cmd

# portsh-cmd.cmd -- the front-end. Env vars for the :ev/JIT subprocesses are set in this shell (so
# they inherit) -- :ev MUST be a subprocess because its abandon is `exit 42` (would kill us otherwise).
{ printf '@echo off\r\n'
  printf 'rem GENERATED by build-portsh-cmd.sh -- portsh cmd two-tier front-end (build %s)\r\n' "$BUILD"
  printf 'setlocal enabledelayedexpansion\r\n'
  printf 'set "HERE=%%~dp0"\r\n'
  printf 'set "PROG=%%~f1"\r\n'
  printf 'set "CACHE=%%LOCALAPPDATA%%\\portsh\\%s"\r\n' "$BUILD"
  printf 'if exist "%%CACHE%%\\.ok" goto warm\r\n'
  printf 'rem ---- COLD: background self-extract (JIT warming) behind the :ev curtain ----\r\n'
  printf 'start "" /b cmd /c call "%%HERE%%_warm.cmd" "%%CACHE%%"\r\n'
  printf 'set "LOG=%%TEMP%%\\portsh-!RANDOM!!RANDOM!.log"\r\n'
  printf 'if exist "!LOG!" del "!LOG!"\r\n'
  printf 'set "PORTSH_LOG=!LOG!"\r\n'
  printf 'set "PORTSH_OK=%%CACHE%%\\.ok"\r\n'
  printf 'cmd /c ""%%HERE%%portsh-full.cmd" "%%PROG%%""\r\n'
  printf 'set "EVRC=!errorlevel!"\r\n'
  printf 'set "PORTSH_LOG=" '"&"' set "PORTSH_OK="\r\n'
  printf 'if "!EVRC!"=="0" goto cleanup\r\n'
  printf 'rem :ev abandoned (42) or crashed (overflow) -> wait for warm, then JIT replays prefix + live\r\n'
  printf ':ww\r\n'
  printf 'if not exist "%%CACHE%%\\.ok" (^>nul ping -n 1 -w 100 127.0.0.1 ^& goto ww)\r\n'
  printf 'set "PORTSH_REPLAY=!LOG!"\r\n'
  printf 'call :runjit\r\n'
  printf 'set "PORTSH_REPLAY="\r\n'
  printf ':cleanup\r\n'
  printf 'del "!LOG!" 2>nul\r\n'
  printf 'endlocal\r\n'
  printf 'goto :eof\r\n'
  printf ':warm\r\n'
  printf 'set "PORTSH_SCRIPT=1"\r\n'
  printf 'call :runjit\r\n'
  printf 'endlocal\r\n'
  printf 'goto :eof\r\n'
  printf 'rem run the cmd JIT on %%PROG%%. The cache is put on PATH (so load-cmd finds comp.cmd / the\r\n'
  printf 'rem per-PC fns / the prim .cmd files) WITHOUT cd-ing there -- the program keeps the USER'"'"'s cwd,\r\n'
  printf 'rem so its relative file paths (read-lines "x") resolve where the user invoked portsh. PORTSH_\r\n'
  printf 'rem REPLAY/SCRIPT (set by the caller) puts load-cmd in script mode (no auto-echo of top values).\r\n'
  printf ':runjit\r\n'
  printf 'set "PATH=%%CACHE%%;%%PATH%%"\r\n'
  printf 'cmd /c "call load-cmd.cmd "%%PROG%%""\r\n'
  printf 'goto :eof\r\n'
} > portsh-cmd.cmd

echo "built portsh-cmd.cmd + _warm.cmd (build $BUILD)"
