#!/bin/sh
# Weave the SHIPPING polyglot `portsh.cmd` -- ONE file, valid as both POSIX sh and Windows batch,
# running the REAL engines (#31):
#   sh  half: the unified always-JIT loader (load-sh.sh) -- file arg = compile+run; no arg = JIT REPL.
#   cmd half: the OSR front-end -- tooling cold = self-extract (the comp-cmd tree is EMBEDDED as a
#             pure-cmd self-extractor section, dispatched via `portsh.cmd __extract DIR`) once per
#             build; program cold = interp + background warmer + flip-as-artifacts-land; warm = all
#             fns flip at first call; no arg = the warming interp REPL.

#
# Dual-validity (same trick as build.sh): the file is CRLF throughout (cmd needs CR for labels); sh
# line 1 re-execs a CR-stripped copy of itself; cmd sees lines 1-2 as ':' labels and `goto`s over the
# entire sh half; sh `exit`s before reaching the batch half, so the megabyte of `echo(` payload lines
# is never parsed by sh.
set -eu
cd "$(dirname "$0")"
[ -f load-sh.sh ] || sh build-load-sh.sh >/dev/null
[ -f comp-cmd/interp-cmd.cmd ] || sh build-interp-cmd.sh >/dev/null
# the AOT stdlib/prims install is part of the shipped tree -- a build-comp-cmd.sh regen (rm -rf)
# drops it, and WITHOUT these guards the polyglot ships with stdlib fns resolvable on the sh half
# but not on cmd (the v0.1.0 bug).
[ -f comp-cmd/map_pc0.cmd ] || sh tools/build-stdlib-aot-cmd.sh >/dev/null
[ -f comp-cmd/__p_add_pc0.cmd ] || sh tools/build-prims-aot-cmd.sh >/dev/null
# _consts_std.cmd in the staleness check: a stdlib reinstall touches it but not interp-cmd.cmd
if [ ! -f comp-cmd.selfx.cmd ] || [ comp-cmd/interp-cmd.cmd -nt comp-cmd.selfx.cmd ] || [ comp-cmd/_consts_std.cmd -nt comp-cmd.selfx.cmd ]; then
  sh tools/pack-comp-cmd.sh >/dev/null
fi
BUILD=$(sed -n 's/^set "PORTSH_BUILD=\([0-9a-f][0-9a-f]*\)".*/\1/p' comp-cmd.selfx.cmd | head -1)
[ -n "$BUILD" ] || { echo "could not read build id from comp-cmd.selfx.cmd"; exit 1; }

python3 - load-sh.sh comp-cmd.selfx.cmd portsh.cmd "$BUILD" <<'PY'
import sys
loadsh, selfx, out, build = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]

# NOTE: the re-exec cooks to a TEMP FILE (not a pipe like build.sh's vau weave) -- a pipe would make
# the inner sh's stdin the script itself, so an interactive REPL (`read` from the user) would consume
# the file's own text. A temp file passes the real stdin through.
hdr = (
  ''':;[ -n "${PORTSH_COOKED-}" ]||{ t=$(mktemp);tr -d '\\r'<"$0">"$t";PORTSH_COOKED=1 PORTSH_SELF="$0" sh "$t" "$@";r=$?;rm -f "$t";exit $r; } #\n'''
  ''':<<'::CMDLITERAL'\n'''
  '''@echo off\n'''
  '''goto :CMDSTART\n'''
  '''::CMDLITERAL\n'''
)

sh_half = open(loadsh, 'rb').read().decode('latin-1')

# ---- pack subcommand + packed-app self-run (shipped polyglot ONLY -- plain load-sh.sh stays a pure
# JIT runner). A packed app is a byte-exact copy of THIS file plus an appended payload: a marker line
# then a PEM base64 block (certutil -encode format) of the program. Both halves exit before the
# payload, so it's inert data; the marker/PEM never appear in the unpacked file (asserted below).
#   pack:        portsh.cmd pack PROG.lisp OUT.cmd  -> OUT = self + base64(PROG) payload
#   packed-run:  a copy with a payload decodes it (sh: sed+base64 -d; cmd: certutil -decode self) and
#                runs it with ALL argv -> the program is compiled+run by the normal engine (cold->warm
#                on cmd via the content-hash cache; JIT on sh). Warm-on-first-run AOT stays pack-app.sh.
sh_pack = (
  '# ---- packed-app + `pack` subcommand (generated by build-polyglot.sh) ----\n'
  '# The PEM header/footer are ASSEMBLED at runtime (the 5 dashes come from $_d5) so the dash-BEGIN\n'
  '# header token never appears literally in the unpacked file -- certutil -decode "%~f0" (cmd side)\n'
  '# treats any such header line as a PEM start, so a literal in THIS code would shadow the real\n'
  '# payload and try to decode source as base64. Only the payload carries it. Asserted at build.\n'
  '_d5=-----; _pb="${_d5}BEGIN CERTIFICATE${_d5}"; _pe="${_d5}END CERTIFICATE${_d5}"\n'
  'if [ "${1:-}" = pack ] && ! grep -q "^__PORTSH_PAYLOAD__$" "$0" 2>/dev/null; then\n'
  '  [ -n "${2:-}" ] && [ -n "${3:-}" ] || { echo "usage: portsh.cmd pack PROG.lisp OUT.cmd" >&2; exit 2; }\n'
  '  [ -f "$2" ] || { echo "portsh pack: $2 not found" >&2; exit 1; }\n'
  '  cp "$PORTSH_SELF" "$3" || exit 1\n'
  '  { printf \'\\r\\n__PORTSH_PAYLOAD__\\r\\n%s\\r\\n\' "$_pb"\n'
  '    base64 < "$2" | tr -d \'\\r\\n\' | fold -w 64 | awk \'{printf "%s\\r\\n", $0}\'\n'
  '    printf \'%s\\r\\n\' "$_pe"\n'
  '  } >> "$3"\n'
  '  chmod +x "$3" 2>/dev/null\n'
  '  echo "packed $3"; exit 0\n'
  'fi\n'
  'if grep -q "^__PORTSH_PAYLOAD__$" "$0" 2>/dev/null; then\n'
  '  _pp=$(mktemp); trap \'rm -f "$_pp"\' EXIT\n'
  '  sed -n "/^$_pb/,/^$_pe/p" "$0" | sed \'1d;$d\' | base64 -d > "$_pp" 2>/dev/null\n'
  '  PORTSH_SCRIPT=${PORTSH_SCRIPT-1}; export PORTSH_SCRIPT\n'
  '  set -- "$_pp" "$@"\n'
  'fi\n'
)
anchor = 'if [ "$#" -lt 1 ]; then jit_repl; exit $?; fi'
assert sh_half.count(anchor) == 1, "sh dispatch anchor not found"
sh_half = sh_half.replace(anchor, sh_pack + anchor, 1)

# the embedded self-extractor: take the selfx body from its `setlocal disableDelayedExpansion` line on,
# rebinding PSDIR to %~2 (the __extract dispatch passes the dest as arg 2). Drop its usage check.
sx = open(selfx, 'rb').read().decode('latin-1').replace('\r\n', '\n')
sx_lines = sx.split('\n')
start = next(i for i, l in enumerate(sx_lines) if l.startswith('setlocal disableDelayedExpansion'))
body = []
for l in sx_lines[start:]:
    if l.startswith('set "PSDIR=%~1"'):
        body.append('set "PSDIR=%~2"')
    elif l.startswith('if "%PSDIR%"=="" '):
        continue
    else:
        body.append(l)
sx_body = '\n'.join(body).rstrip('\n')

cmd_half = '''@echo off
rem ============ portsh cmd OSR front-end (build {B}) -- generated by build-polyglot.sh ============
if "%~1"=="__extract" goto :PSELFX
if "%~1"=="__warm" goto :PWARM
setlocal enabledelayedexpansion
set "CACHE=%LOCALAPPDATA%\\portsh\\{B}"
if exist "%CACHE%\\.ok" goto pcache_ok
rem tooling cold: self-extract the embedded comp-cmd tree, once per build (atomic: tmp -> move -> .ok)
if exist "%CACHE%.tmp" rmdir /s /q "%CACHE%.tmp"
cmd /c call "%~f0" __extract "%CACHE%.tmp" >nul 2>&1
move "%CACHE%.tmp" "%CACHE%" >nul 2>&1
rem promote only a COMPLETE extraction (a failed extract/move must not poison the cache with .ok)
if exist "%CACHE%\\interp-cmd.cmd" break>"%CACHE%\\.ok"
:pcache_ok
set "PATH=%CACHE%;%PATH%"
rem packed app? (a copy of this file with an appended payload) -> decode + run it, ALL args are the program's.
findstr /b /x /c:"__PORTSH_PAYLOAD__" "%~f0" >nul 2>&1 && goto :PPACKED
if /i "%~1"=="pack" goto :PPACK
if "%~1"=="" goto prepl
set "PROG=%~f1"
rem capture user args (after the program path) into PORTSH_ARGV_<n>/PORTSH_ARGC for (argv) -- env
rem vars inherit into the interp child, so nothing needs re-quoting downstream.
set "PORTSH_ARGC=0"
:pargs
if "%~2"=="" goto pargs_done
set "PORTSH_ARGV_!PORTSH_ARGC!=%~2"
set /a PORTSH_ARGC+=1
shift /2
goto pargs
:pargs_done
:phash
rem program cache key = content hash (edits invalidate; identical content reuses)
set "H="
for /f "skip=1 tokens=1" %%h in ('certutil -hashfile "!PROG!" SHA256') do if not defined H set "H=%%h"
set "PCACHE=%CACHE%\\p\\!H:~0,16!"
if not exist "%CACHE%\\p" mkdir "%CACHE%\\p"
if exist "!PCACHE!\\.ok" goto prun
rem program cold: launch the MANIFEST-WATCHER warmer (the :PWARM arm of this file) DETACHED via the
rem Task Scheduler (a `start /b` child dies with this console/ssh job; a task survives -- fallback to
rem start /b if schtasks is unavailable). The runtime-generated script is a 2-line trampoline with
rem CONCRETE paths (so the schtasks action needs no nested quoting); all logic is static in :PWARM.
set "WARMP=%TEMP%\\portsh_warmp_!H:~0,16!.cmd"
> "!WARMP!" echo @echo off
>>"!WARMP!" echo call "%~f0" __warm "!PROG!" "!PCACHE!" "!PCACHE!.stage" "portsh_w_!H:~0,16!"
set "WOK="
schtasks /create /f /tn "portsh_w_!H:~0,16!" /tr "'!WARMP!'" /sc once /st 00:00 >nul 2>&1 && set "WOK=1"
if defined WOK (schtasks /run /tn "portsh_w_!H:~0,16!" >nul 2>&1) else (start "" /b cmd /c ""!WARMP!"" >nul 2>&1)
:prun
set "PORTSH_OSRDIR=!PCACHE!"
set "PORTSH_SCRIPT=1"
cmd /c "call interp-cmd.cmd "!PROG!""
set "RC=!errorlevel!"
endlocal & exit /b %RC%
:prepl
rem the REPL is the warming interpreter (per-input background compile + flip)
cmd /c "call interp-cmd.cmd"
set "RC=!errorlevel!"
endlocal & exit /b %RC%
:PPACK
rem pack PROG OUT: OUT = byte-exact copy of this file + appended payload (marker + PEM base64 of PROG).
rem copy /b is binary-exact (preserves CRLF + the polyglot); the leading blank echo guarantees the
rem marker starts its own line regardless of the file's final byte. certutil -encode emits the PEM block
rem (the same form the sh half writes); certutil -decode / base64 -d read it back on either host.
if "%~3"=="" (echo usage: portsh.cmd pack PROG.lisp OUT.cmd 1>&2 & endlocal & exit /b 2)
if not exist "%~2" (echo portsh pack: %~2 not found 1>&2 & endlocal & exit /b 1)
copy /b "%~f0" "%~3" >nul 2>&1 || (echo portsh pack: cannot write %~3 1>&2 & endlocal & exit /b 1)
>>"%~3" echo(
>>"%~3" echo(__PORTSH_PAYLOAD__
set "PPENC=%TEMP%\\pp_enc_!RANDOM!!RANDOM!.tmp"
certutil -encode "%~2" "!PPENC!" >nul 2>&1
for /f "usebackq delims=" %%t in ("!PPENC!") do >>"%~3" echo(%%t
del "!PPENC!" >nul 2>&1
echo packed %~3
endlocal & exit /b 0
:PPACKED
rem this file carries an embedded program -> decode it (certutil scans for the PEM block, ignoring the
rem leading polyglot bytes) and run it through the normal content-hash cache path. ALL args are argv.
set "PPROG=%TEMP%\\pp_run_!RANDOM!!RANDOM!.lisp"
certutil -decode "%~f0" "!PPROG!" >nul 2>&1
set "PORTSH_ARGC=0"
:ppargs
if "%~1"=="" goto ppargs_done
set "PORTSH_ARGV_!PORTSH_ARGC!=%~1"
set /a PORTSH_ARGC+=1
shift /1
goto ppargs
:ppargs_done
set "PROG=!PPROG!"
goto phash
:PWARM
rem %2=prog %3=pcache %4=stage %5=taskname -- the MANIFEST-WATCHER warmer (runs detached). The whole-
rem program compile (heap-safe, emits everything incl clambdas) runs as a background CHILD writing into
rem STAGE; this process watches STAGE\\_main: cp appends fn X's manifest line AFTER X's segments are
rem fully written, and X's clambdas (no manifest lines) land before the NEXT manifest -- so each new
rem manifest publishes the newly-manifested fn at once and __lam files with a ONE-EVENT lag. Every
rem publish is per-file ATOMIC (copy to .t + move): a kill can never leave a truncated artifact.
rem _consts/_thunks/.ok publish only at _done, so the warm fast path and the front-end's skip-spawn
rem check only ever see complete caches; a killed warmer leaves only complete fns (the live run flips
rem them mid-run; the next warmer re-runs the compile and fills the rest -- monotonic).
setlocal enabledelayedexpansion
set "WPROG=%~2"
set "WPUB=%~3"
set "WSTG=%~4"
set "WTASK=%~5"
set "PATH=%LOCALAPPDATA%\\portsh\\{B};!PATH!"
if exist "!WSTG!" rmdir /s /q "!WSTG!"
mkdir "!WSTG!"
if not exist "!WPUB!" mkdir "!WPUB!"
> "!WSTG!\\_run.cmd" echo @call interp-cmd.cmd "!WPROG!" ^>nul 2^>^&1
>>"!WSTG!\\_run.cmd" echo @break^>"!WSTG!\\_done"
set "PORTSH_OSRCOMPILE=!WSTG!"
start "" /b cmd /c ""!WSTG!\\_run.cmd"" >nul 2>&1
set "PORTSH_OSRCOMPILE="
set "WNPUB=0"
set "WPLAMS="
:pw_poll
set "WNMAN=0"
if exist "!WSTG!\\_main" for /f "usebackq delims=" %%L in ("!WSTG!\\_main") do set /a WNMAN+=1
if !WNMAN! GTR !WNPUB! call :pw_event
if exist "!WSTG!\\_done" goto pw_finish
>nul ping -n 2 -w 200 127.0.0.1
goto pw_poll
:pw_event
set "WI=0"
rem manifest lines are `(define <nm> (make-compiled "<mangled>"))` -- with DEFAULT delims token 1 is
rem `(define`, so token 2 is the bare name. Do NOT put `)` in a delims= spec: cmd's parser treats it
rem as a block close and kills the whole for /f line ("`)` was unexpected"), silently in a detached
rem process. (That bug shipped first: zero per-fn publishes, everything swept at _done.)
for /f "usebackq tokens=2" %%n in ("!WSTG!\\_main") do (
  if !WI! GEQ !WNPUB! (set "WM=%%n" & call :pw_mangle & call :pw_pub "!WL!")
  set /a WI+=1
)
for %%l in (!WPLAMS!) do call :pw_pub "%%~l"
set "WPLAMS="
for %%f in ("!WSTG!\\__lam*_pc0.cmd") do (set "WLB=%%~nf" & set "WLB=!WLB:_pc0=!" & set "WPLAMS=!WPLAMS! !WLB!")
set "WNPUB=!WNMAN!"
goto :eof
:pw_finish
for %%f in ("!WSTG!\\*_pc0.cmd") do (set "WLB=%%~nf" & set "WLB=!WLB:_pc0=!" & call :pw_pub "!WLB!")
if exist "!WSTG!\\_consts.cmd" (copy "!WSTG!\\_consts.cmd" "!WPUB!\\_consts.cmd.t" >nul & move /y "!WPUB!\\_consts.cmd.t" "!WPUB!\\_consts.cmd" >nul)
if exist "!WSTG!\\_thunks" (copy "!WSTG!\\_thunks" "!WPUB!\\_thunks.t" >nul & move /y "!WPUB!\\_thunks.t" "!WPUB!\\_thunks" >nul)
break>"!WPUB!\\.ok"
rmdir /s /q "!WSTG!" 2>nul
schtasks /delete /f /tn "!WTASK!" >nul 2>&1
endlocal
exit /b 0
:pw_pub
for %%f in ("!WSTG!\\%~1_pc*.cmd") do (
  echo %%~nxf | findstr /e "_pc0.cmd" >nul || call :pw_pubf "%%f" "%%~nxf"
)
for %%f in ("!WSTG!\\%~1_pc0.cmd") do call :pw_pubf "%%f" "%%~nxf"
goto :eof
:pw_pubf
if exist "!WPUB!\\%~2" goto :eof
copy "%~1" "!WPUB!\\%~2.t" >nul 2>&1
move /y "!WPUB!\\%~2.t" "!WPUB!\\%~2" >nul 2>&1
goto :eof
:pw_mangle
set "WL="
set "WMS=!WM!"
:pw_m2
if not defined WMS goto :eof
set "WMC=!WMS:~0,1!"
set "WMS=!WMS:~1!"
if "!WMC!"=="<" (set "WL=!WL!zzL" & goto pw_m2)
if "!WMC!"==">" (set "WL=!WL!zzG" & goto pw_m2)
if "!WMC!"=="&" (set "WL=!WL!zzA" & goto pw_m2)
if "!WMC!"=="|" (set "WL=!WL!zzP" & goto pw_m2)
if "!WMC!"=="*" (set "WL=!WL!zzS" & goto pw_m2)
if "!WMC!"=="?" (set "WL=!WL!zzQ" & goto pw_m2)
set "WL=!WL!!WMC!"
goto pw_m2
:PSELFX
{SX}
exit /b 0
'''.replace('{B}', build).replace('{SX}', sx_body)

whole = hdr + sh_half.rstrip('\n') + '\nexit $?\n:CMDSTART\n' + cmd_half
whole = whole.replace('\r\n', '\n').replace('\n', '\r\n')
# the marker is detected on its OWN line (grep ^$ / findstr /x) -> must not occur bare in the unpacked
# file; the PEM header/footer are scanned ANYWHERE by certutil -decode -> must not occur AT ALL (the
# code assembles them from fragments). Either would make portsh.cmd misread itself as a packed app.
assert ('\n__PORTSH_PAYLOAD__\r\n') not in whole and not whole.startswith('__PORTSH_PAYLOAD__\r\n'), \
    "pack marker appears bare in the unpacked polyglot"
for pem in ('-----BEGIN', '-----END'):
    assert pem not in whole, "PEM header token %r appears in the unpacked polyglot (certutil would mis-scan)" % pem
open(out, 'wb').write(whole.encode('latin-1'))
PY
# `./portsh.cmd` must work directly. A shebang is impossible (cmd would echo it as an error before
# @echo off), so this rides the POSIX ENOEXEC fallback: an executable file without a shebang is run
# as an sh script by the invoking shell, and line 1 re-execs the CR-stripped copy and exits before
# anything else is parsed.
chmod +x portsh.cmd
echo "built portsh.cmd ($(wc -c < portsh.cmd) bytes, build $BUILD)"
