(setenv "PORTSH_SET_X" "from-lisp")
(print (getenv "PORTSH_SET_X"))
(setenv "PORTSH_SET_X" "")
(print (getenv "PORTSH_SET_X"))
(print (setenv "bad name" "x"))
(print (make-dir "pk_t/sub"))
(write-lines "pk_t/sub/a.txt" (list "one" "two"))
(print (file-exists? "pk_t/sub/a.txt"))
(print (copy-file "pk_t/sub/a.txt" "pk_t/sub/b.txt"))
(print (car (read-lines "pk_t/sub/b.txt")))
(print (delete-file "pk_t/sub/a.txt"))
(print (file-exists? "pk_t/sub/a.txt"))
(print (delete-file "pk_t/sub/a.txt"))
(print (delete-file "pk_t/sub/b.txt"))
