(setenv "PORTSH_SET_X" "from-lisp")
(print (getenv "PORTSH_SET_X"))
(setenv "PORTSH_SET_X" "")
(print (getenv "PORTSH_SET_X"))
(print (setenv "bad name" "x"))
(print (make-dir "pk_t/sub"))
(write-lines "pk_t/sub/a.txt" (list "one" "two"))
(print (file-exists? "pk_t/sub/a.txt"))
(print (copy-file "pk_t/sub/a.txt" "pk_t/sub/b.txt"))
(print (car (read-lines "pk_t/sub/b.txt")))
(print (delete-file "pk_t/sub/a.txt"))
(print (file-exists? "pk_t/sub/a.txt"))
(print (delete-file "pk_t/sub/a.txt"))
(print (delete-file "pk_t/sub/b.txt"))
; (host) is the one host-DIVERGENT primitive (sh|cmd by design) -- pin it portably: it must be
; one of the two symbols, and it must agree with itself as a value and across calls.
(print (if (eq? (host) (quote sh)) (quote ok) (if (eq? (host) (quote cmd)) (quote ok) (quote bad))))
(print (eq? (host) (host)))
