(print "a;b")
(print (string-append "i;" "j;k"))
(print (string-length ""))
(print (string-append "" ""))
(print (string-length (string-append "ab" "")))
(print (split "a,b,c" ","))
(print (split "a,,b" ","))
(print (split "abc" ","))
(print (split "aXXbXXc" "XX"))
(print (string-downcase "MiXeD-42_OK"))
(print (string-upcase "MiXeD-42_ok"))
(print (string-downcase ""))
(print (eq? (string-downcase "ABC0DEF") "abc0def"))
