(print "a;b")
(print (string-append "i;" "j;k"))
(print (string-length ""))
(print (string-append "" ""))
(print (string-length (string-append "ab" "")))
(print (split "a,b,c" ","))
(print (split "a,,b" ","))
(print (split "abc" ","))
(print (split "aXXbXXc" "XX"))
