; The gaps closed after v0.1.0 (task #45): > >= as chain builtins, value-position primitives and
; type predicates (__p_ wrappers), str/begin as first-class values (variadic stdlib AOT), literal
; nil defines, and bare-symbol fn aliasing ((define f g) evaluates g at define time).
(print (> 3 1))
(print (>= 2 3))
(print (> 5 3 1))
(print (>= 5 5 4 4))
(print (> 5 3 3))
(define app1 (lambda (f x) (f x)))
(define app2 (lambda (f a b) (f a b)))
(print (app2 > 5 2))
(print (app2 >= 2 5))
(print (app2 <= 2 5))
(print (app2 < 1 2))
(print (app1 number? 4))
(print (app1 number? "x"))
(print (app1 string? "x"))
(print (app1 symbol? (quote s)))
(print (app1 str 42))
(define mystr str)
(print (mystr "n=" 7))
(define mylen length)
(print (mylen (quote (a b c))))
(define z nil)
(print (null? z))
(define w t)
(print w)
; print as a VALUE (__p_print): the map itself prints a/b/c, the outer print shows map's result
(print (map print (quote (a b c))))
