(define ls (lambda args args))
(print (ls 1 2 3 4))
(print (ls))
(define rest2 (lambda (a b) (cons a b)))
(print (apply ls (list 7 8)))
(define tagger (lambda (tg) (lambda rest (cons tg rest))))
(define tagx (tagger (quote x)))
(print (tagx 10 20))
(define sumall (lambda nums (foldl + 0 nums)))
(define foldl (lambda (f acc xs) (if (null? xs) acc (foldl f (f acc (car xs)) (cdr xs)))))
(print (sumall 1 2 3 4 5))
