(print (type-of 5))
(print (type-of "x"))
(print (type-of (quote a)))
(print (type-of (cons 1 2)))
(print (type-of car))
(define f (read "(+ 2 3)"))
(print (type-of f))
(print (car f))
(print (car (cdr f)))
