#!/bin/sh
# Compile the AOT-able applicative subset of src/stdlib.lisp -> src/stdlib-aot.sh, using the native
# sh-emitter comp-sh.sh. The eval/load runtimes embed this so programs can call map/foldl/filter/
# assoc/... by name -- no interpreter, no per-run stdlib load.
#
# SKIPS (compiled code doesn't need them / comp can't compile them):
#   - vau forms (and/or/when/unless/cond/let/let*/case/apply) -> comp-derived (or deferred: apply)
#   - variadic lambdas (begin/str) -> (lambda args ...) is uncompilable (comp is fixed-arity); also
#     `begin`/`str` are comp special forms anyway
#   - the comp-inlined type predicates (number?/string?/symbol?/pair?)
# Note: comp-sh-compiled.sh is the sh-EMITTER's core (self-contained, DEPS=""), so it does NOT
# provide caar/cadr/.../reverse/assoc -- the stdlib must. (`append` self-defined there too is a
# harmless identical re-def.)
set -eu
cd "$(dirname "$0")/.."
[ -f comp-sh.sh ] || sh build-comp-sh.sh >/dev/null
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT

python3 - src/stdlib.lisp "$work/sub.lisp" <<'PY'
import sys, re
src_path, out = sys.argv[1], sys.argv[2]
skip_names = {'number?','string?','symbol?','pair?'}  # comp inlines these (tpreds)
def forms(s):
    i=0;n=len(s)
    while i<n:
        while i<n and s[i]!='(':
            if i<n and s[i]==';':
                while i<n and s[i]!='\n': i+=1
            i+=1
        if i>=n: break
        d=0;j=i;instr=False;cm=False
        while j<n:
            c=s[j]
            if cm:
                if c=='\n': cm=False
            elif instr:
                if c=='"': instr=False
            else:
                if c==';': cm=True
                elif c=='"': instr=True
                elif c=='(': d+=1
                elif c==')':
                    d-=1
                    if d==0: j+=1; break
            j+=1
        yield s[i:j]; i=j
keep=[]
for f in forms(open(src_path).read()):
    m=re.match(r'\(define\s+([^\s()]+)\s+(.*)', f, re.S)
    if not m: continue
    name, body = m.group(1), m.group(2).lstrip()
    if name in skip_names: continue
    if body.startswith('(vau'): continue                 # vau operative -> comp-derived / deferred
    lm=re.match(r'\(lambda\s+(\S)', body)                 # variadic (lambda args ...) -> uncompilable
    if lm and lm.group(1) != '(': continue
    keep.append(f)
open(out,'w').write('('+'\n'.join(keep)+'\n)')
sys.stderr.write("AOT stdlib fns: %d\n" % len(keep))
PY

mksh comp-sh.sh "$work/sub.lisp" "$work/fns.sh"
# Namespace the stdlib's lifted closures (__lamN -> __slN) so they don't COLLIDE with a user
# program's own __lamN -- both lift-counters start at 0, and the runtime embeds this stdlib
# alongside freshly-compiled user code (consistent rename: defs, SIZE_, and the S:<label> refs).
sed 's/__lam/__sl/g' "$work/fns.sh" > "$work/fns2.sh"
{ echo "# src/stdlib-aot.sh -- AOT-compiled applicative stdlib (native sh), GENERATED by"
  echo "# tools/build-stdlib-aot.sh from src/stdlib.lisp via comp-sh.sh. Embedded in the eval/load runtimes."
  cat "$work/fns2.sh"
} > src/stdlib-aot.sh
echo "wrote src/stdlib-aot.sh ($(grep -c ') {' src/stdlib-aot.sh) fns, $(wc -l < src/stdlib-aot.sh) lines)"
