#!/bin/sh
# Compile src/prims.lisp (the value-position primitive wrappers __p_add/__p_cons/...) to native sh
# via comp-sh.sh -> src/prims-aot.sh, embedded in the eval/load runtimes. When a primitive is used as
# a VALUE (e.g. (foldr + 0 xs)), lval (prim-wrap) compiles it to C:__p_<op>, which dispatches to one
# of these fns. The wrappers use the primitives in CALL position only, so they compile cleanly (no
# inline lambdas -> no __lam lifting -> no namespacing needed).
set -eu
cd "$(dirname "$0")/.."
[ -f comp-sh.sh ] || sh build-comp-sh.sh >/dev/null
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT
{ printf '('; cat src/prims.lisp; printf ')'; } > "$work/p.lisp"
mksh comp-sh.sh "$work/p.lisp" "$work/p.sh"
{ echo "# src/prims-aot.sh -- primitive value-wrappers (src/prims.lisp) compiled to native sh by"
  echo "# comp-sh.sh. GENERATED by tools/build-prims-aot.sh. Embedded in eval/load so value-position"
  echo "# primitives ((foldr + 0 xs), (map car ps), ...) resolve to C:__p_<op> fns."
  cat "$work/p.sh"
} > src/prims-aot.sh
echo "wrote src/prims-aot.sh ($(grep -c ') {' src/prims-aot.sh) fns)"
