#!/bin/sh
# Generate comp-cmd.selfx.cmd -- a PURE-CMD self-extractor for the comp-cmd/ runtime tree (the cmd
# JIT: ~1400 per-PC .cmd files). No external tools (no tar/certutil/powershell) -> absolute Windows
# portability. Each file is written with ONE block-redirect of `echo(`-emitted lines under
# `setlocal disableDelayedExpansion` (so `!` is literal -- comp-cmd is saturated with !var!); the
# build-time escaper handles ^ & | < > ( ) and % -> %%. Usage at runtime: `comp-cmd.selfx.cmd DESTDIR`
# writes the whole tree into DESTDIR. The polyglot front-end embeds this past the marker and runs it
# (backgrounded, atomic-rename) on a cold first run. A content-hash build id keys the cache dir.
set -eu
cd "$(dirname "$0")/.."
[ -d comp-cmd ] || { echo "comp-cmd/ missing (run build-comp-cmd.sh)"; exit 1; }
python3 - comp-cmd comp-cmd.selfx.cmd <<'PY'
import sys, os, hashlib
srcdir, out = sys.argv[1], sys.argv[2]
files = sorted(f for f in os.listdir(srcdir) if os.path.isfile(os.path.join(srcdir, f)))
h = hashlib.sha256()
for f in files:
    h.update(f.encode())
    h.update(open(os.path.join(srcdir, f), 'rb').read())
build = h.hexdigest()[:12]
def esc(s):
    # cmd `^` escaping is active ONLY outside double-quotes; inside "..." the specials & | < > ( ) ^
    # are literal and a `^` would leak. So track quote parity and escape only outside quotes. `%`->`%%`
    # always (percent-doubling is quote-independent in a batch file); `!` stays literal (delayed exp off).
    out = []; inq = False
    for c in s:
        if c == '"':   out.append('"'); inq = not inq
        elif c == '%': out.append('%%')
        elif c == '^': out.append('^' if inq else '^^')
        elif c in '&|<>()': out.append(c if inq else '^' + c)
        else: out.append(c)
    return ''.join(out)
o = open(out, 'w', newline='\r\n', encoding='latin-1')   # byte-preserving (matches the latin-1 read; keeps UTF-8 bytes like — intact)
o.write('@echo off\n')
o.write('rem GENERATED by tools/pack-comp-cmd.sh -- pure-cmd self-extractor for comp-cmd/ (build %s)\n' % build)
o.write('set "PORTSH_BUILD=%s"\n' % build)
o.write('setlocal disableDelayedExpansion\n')
o.write('set "PSDIR=%~1"\n')
o.write('if "%PSDIR%"=="" (echo usage: %~nx0 DESTDIR & exit /b 1)\n')
o.write('if not exist "%PSDIR%" md "%PSDIR%"\n')
nlines = 0
for f in files:
    data = open(os.path.join(srcdir, f), 'rb').read().decode('latin-1')
    if data == '':
        o.write('break>"%%PSDIR%%\\%s"\n' % f)
        continue
    lines = data.split('\n')
    if lines and lines[-1] == '':
        lines = lines[:-1]   # drop the empty trailing element from a final newline
    o.write('>"%%PSDIR%%\\%s" (\n' % f)
    for ln in lines:
        nlines += 1
        o.write('echo(' + esc(ln.rstrip('\r')) + '\n')
    o.write(')\n')
o.write('>"%PSDIR%\\.ok" echo ' + build + '\n')
o.write('endlocal\n')
sys.stderr.write("build=%s files=%d echo-lines=%d\n" % (build, len(files), nlines))
PY
echo "wrote comp-cmd.selfx.cmd ($(wc -c < comp-cmd.selfx.cmd) bytes)"
