#!/bin/sh
# Generate comp-cmd.selfx.cmd -- a PURE-CMD self-extractor for the comp-cmd/ runtime tree (the cmd
# JIT: ~1400 per-PC .cmd files). No external tools (no tar/certutil/powershell) -> absolute Windows
# portability. Each file is written with ONE block-redirect of `echo(`-emitted lines under
# `setlocal disableDelayedExpansion` (so `!` is literal -- comp-cmd is saturated with !var!); the
# build-time escaper handles ^ & | < > ( ) and % -> %%. Usage at runtime: `comp-cmd.selfx.cmd DESTDIR`
# writes the whole tree into DESTDIR. The polyglot front-end embeds this past the marker and runs it
# (backgrounded, atomic-rename) on a cold first run. A content-hash build id keys the cache dir.
set -eu
cd "$(dirname "$0")/.."
[ -d comp-cmd ] || { echo "comp-cmd/ missing (run build-comp-cmd.sh)"; exit 1; }
# MODE full (default): the whole tree -> comp-cmd.selfx.cmd (embedded by portsh.cmd, which needs the
# compiler for its JIT/watcher). MODE rt: runtime-only subset -> comp-cmd.selfx-rt.cmd (embedded by
# packed apps, which never compile: AOT happens at pack time, and `eval` is not a compiled builtin).
# rt = the _rt.lst pc files (stdlib + prims + comp's 7 stdlib deps, written by the AOT installers)
# + every non-pc side file except the compiler driver/manifest and the standalone test engines. Its
# build id hashes the SUBSET -> packed apps cache under their own %LOCALAPPDATA%\portsh\<id>, fully
# decoupled from the full tooling cache (a partial tree can never poison portsh.cmd's cache).
MODE=${1:-full}
case $MODE in
  full) OUT=comp-cmd.selfx.cmd ;;
  rt)   OUT=comp-cmd.selfx-rt.cmd
        [ -f comp-cmd/_rt.lst ] || { echo "comp-cmd/_rt.lst missing -- run tools/build-stdlib-aot-cmd.sh + tools/build-prims-aot-cmd.sh" >&2; exit 1; } ;;
  *)    echo "usage: sh tools/pack-comp-cmd.sh [full|rt]" >&2; exit 1 ;;
esac
python3 - comp-cmd "$OUT" "$MODE" <<'PY'
import sys, os, hashlib, re
srcdir, out, mode = sys.argv[1], sys.argv[2], sys.argv[3]
# load-cmd.cmd / eval-cmd.cmd are the standalone cmd-JIT engines -- dev/test artifacts (engine-
# differential + stdlib-cmd tests); nothing in the shipped front-end calls them. Excluding them keeps
# the pack lean AND the build id deterministic regardless of whether their builders have run since
# the last comp-cmd/ regen.
EXCLUDE = {'load-cmd.cmd', 'eval-cmd.cmd'}
files = sorted(f for f in os.listdir(srcdir)
               if os.path.isfile(os.path.join(srcdir, f)) and f not in EXCLUDE)
if mode == 'rt':
    rt = set(open(os.path.join(srcdir, '_rt.lst')).read().split())
    is_pc = re.compile(r'.*_pc\d+\.cmd$')
    EXCLUDE_RT = {'comp.cmd', 'main.lisp'}   # the compiler driver + its compiled-fn manifest
    files = [f for f in files if (f in rt) or (not is_pc.match(f) and f not in EXCLUDE_RT)]
h = hashlib.sha256()
for f in files:
    h.update(f.encode())
    h.update(open(os.path.join(srcdir, f), 'rb').read())
build = h.hexdigest()[:12]
def esc(s):
    # cmd `^` escaping is active ONLY outside double-quotes; inside "..." the specials & | < > ( ) ^
    # are literal and a `^` would leak. So track quote parity and escape only outside quotes. `%`->`%%`
    # always (percent-doubling is quote-independent in a batch file); `!` stays literal (delayed exp off).
    out = []; inq = False
    for c in s:
        if c == '"':   out.append('"'); inq = not inq
        elif c == '%': out.append('%%')
        elif c == '^': out.append('^' if inq else '^^')
        elif c in '&|<>()': out.append(c if inq else '^' + c)
        else: out.append(c)
    return ''.join(out)
o = open(out, 'w', newline='\r\n', encoding='latin-1')   # byte-preserving (matches the latin-1 read; keeps UTF-8 bytes like — intact)
o.write('@echo off\n')
o.write('rem GENERATED by tools/pack-comp-cmd.sh -- pure-cmd self-extractor for comp-cmd/ (build %s)\n' % build)
o.write('set "PORTSH_BUILD=%s"\n' % build)
o.write('setlocal disableDelayedExpansion\n')
o.write('set "PSDIR=%~1"\n')
o.write('if "%PSDIR%"=="" (echo usage: %~nx0 DESTDIR & exit /b 1)\n')
o.write('if not exist "%PSDIR%" md "%PSDIR%"\n')
nlines = 0
for f in files:
    data = open(os.path.join(srcdir, f), 'rb').read().decode('latin-1')
    if data == '':
        o.write('break>"%%PSDIR%%\\%s"\n' % f)
        continue
    lines = data.split('\n')
    if lines and lines[-1] == '':
        lines = lines[:-1]   # drop the empty trailing element from a final newline
    o.write('>"%%PSDIR%%\\%s" (\n' % f)
    for ln in lines:
        nlines += 1
        o.write('echo(' + esc(ln.rstrip('\r')) + '\n')
    o.write(')\n')
o.write('>"%PSDIR%\\.ok" echo ' + build + '\n')
o.write('endlocal\n')
sys.stderr.write("build=%s files=%d echo-lines=%d\n" % (build, len(files), nlines))
PY
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
