#!/bin/sh
# FAST regeneration of comp-compiled.sh (comp.sh's core) using the native sh-emitter comp-sh.sh,
# instead of the ~30-55min interpreted tools/bootstrap-comp.sh. Run after editing src/compile.lisp
# (and/or src/compile-sh.lisp). ~4-7 min vs ~30-55min. Validate afterward with tests/native-comp.sh.
#
# If src/compile-sh.lisp changed, comp-sh.sh must first re-self-host (it embeds compile-sh.lisp):
#   comp-sh.sh self-compiles compile-sh.lisp -> comp-sh-compiled.sh -> rebuild comp-sh.sh.
# Then comp-sh.sh compiles (stdlib deps + compile.lisp) -> comp-compiled.sh.
#
# Falls back to the interpreted bootstrap if comp-sh.sh is absent (first-time build). After a
# compile-sh.lisp change a second `regen` pass reaches the fixpoint if the change is self-affecting.
set -eu
cd "$(dirname "$0")/.."

if [ ! -f comp-sh.sh ]; then
  echo "comp-sh.sh absent -> first-time interpreted build (slow). Run: sh build-comp-sh.sh"
  exit 1
fi

work=$(mktemp -d); trap 'rm -rf "$work"' EXIT

# 1. re-self-host: comp-sh.sh compiles compile-sh.lisp -> comp-sh-compiled.sh; rebuild comp-sh.sh.
echo "regen comp-sh-compiled.sh (self-host) ..."
{ printf '('; cat src/compile-sh.lisp; printf ')'; } > "$work/csh.lisp"
mksh comp-sh.sh "$work/csh.lisp" "$work/csh-fns.sh"
{ echo "# src/comp-sh-compiled.sh — compile-sh.lisp self-compiled to native sh by comp-sh.sh."
  echo "# GENERATED by tools/regen-comp.sh. The native Lisp->sh emitter (see build-comp-sh.sh)."
  cat "$work/csh-fns.sh"
} > src/comp-sh-compiled.sh
sh build-comp-sh.sh >/dev/null   # reassembles comp-sh.sh from the fresh comp-sh-compiled.sh

# 2. comp-sh.sh compiles (stdlib deps + compile.lisp) -> comp-compiled.sh.
echo "regen comp-compiled.sh ..."
python3 - src/stdlib.lisp src/compile.lisp "$work/cinput.lisp" <<'PY'
import sys,re
stdlib,comp,outp=sys.argv[1:4]
deps={'caar','cadr','caddr','not','append','reverse','assoc'}
def forms(s):
    i=0;n=len(s)
    while i<n:
        while i<n and s[i]!='(':
            if i<n and s[i]==';':
                while i<n and s[i]!='\n': i+=1
            i+=1
        if i>=n: break
        d=0;j=i;instr=False;cm=False
        while j<n:
            c=s[j]
            if cm:
                if c=='\n': cm=False
            elif instr:
                if c=='"': instr=False
            else:
                if c==';': cm=True
                elif c=='"': instr=True
                elif c=='(': d+=1
                elif c==')':
                    d-=1
                    if d==0: j+=1; break
            j+=1
        yield s[i:j]; i=j
keep=[f for f in forms(open(stdlib).read()) if (m:=re.match(r'\(define\s+([^\s()]+)',f)) and m.group(1) in deps]
open(outp,'w').write('('+'\n'.join(keep)+'\n'+open(comp).read()+')')
PY
mksh comp-sh.sh "$work/cinput.lisp" "$work/comp-fns.sh"
{ echo "# src/comp-compiled.sh — compile.lisp + stdlib deps, compiled to native sh by comp-sh.sh"
  echo "# (the native Lisp->sh emitter). Regenerate via tools/regen-comp.sh; validate via tests/native-comp.sh."
  cat "$work/comp-fns.sh"
} > src/comp-compiled.sh

sh build-comp.sh >/dev/null
echo "regenerated src/comp-sh-compiled.sh + src/comp-compiled.sh + comp.sh ($(grep -c ') {' src/comp-compiled.sh) fns). Validate: sh tests/native-comp.sh"
