;;; compile-sh.lisp -- Lisp->sh backend, TRAMPOLINE codegen (basic-block lowering).
;;; Each fn becomes a resumable segment-machine dispatched by a driver loop (build-comp.sh):
;;; host stack depth stays 2 regardless of logical recursion depth. Live data lives in the
;;; frame stack F[0..FP+SIZE_fn); gc_run scans it. Replaces the old direct-call frame-mirror.
;; ===== trampoline codegen (dev) — basic-block lowering. chained-emit style (low nesting). =====
(define cadddr (lambda (x) (car (cdr (cdr (cdr x))))))
(define rev (lambda (xs acc) (if (null? xs) acc (rev (cdr xs) (cons (car xs) acc)))))
(define lookup (lambda (k al) (if (null? al) nil (if (eq? (car (car al)) k) (cdr (car al)) (lookup k (cdr al))))))
(define lenl (lambda (xs) (if (null? xs) 0 (+ 1 (lenl (cdr xs))))))
(define maxi (lambda (a b) (if (< a b) b a)))
(define append (lambda (a b) (if (null? a) b (cons (car a) (append (cdr a) b)))))
;; free-variable analysis for flat closures: symbols in a form not bound by an enclosing
;; lambda/let (over-collects globals/prims; caller intersects with pmap for the capture set).
(define mem? (lambda (x xs) (if (null? xs) nil (if (eq? x (car xs)) t (mem? x (cdr xs))))))
(define set-add (lambda (x xs) (if (mem? x xs) xs (cons x xs))))
(define lv-names (lambda (binds) (if (pair? binds) (cons (car (car binds)) (lv-names (cdr binds))) nil)))
(define fv-binds (lambda (binds bound acc) (if (pair? binds) (fv-binds (cdr binds) bound (fv (car (cdr (car binds))) bound acc)) acc)))
(define fv-list (lambda (fs bound acc) (if (pair? fs) (fv-list (cdr fs) bound (fv (car fs) bound acc)) acc)))
(define fv (lambda (f bound acc)
  (if (pair? f)
    (if (eq? (car f) (quote quote)) acc
      (if (eq? (car f) (quote lambda)) (fv (car (cdr (cdr f))) (append (car (cdr f)) bound) acc)
        (if (eq? (car f) (quote let))
          (fv (car (cdr (cdr f))) (append (lv-names (car (cdr f))) bound) (fv-binds (car (cdr f)) bound acc))
          (fv-list f bound acc))))
    (if (symbol? f) (if (mem? f bound) acc (set-add f acc)) acc))))
;; lambda-lift: hoist each inline (lambda lf lb) to a top-level (define __lamN (clambda lf cap lb))
;; and replace it with (make-closure (quote __lamN) cap...). cap = free vars of the lambda that are
;; bound in the ENCLOSING scope (fv ∩ bound). Returns (form' lifted-defs next-ctr); threads ctr for
;; fresh names + bound for capture. (TODO: track let-bound names in `bound` for let-nested lambdas.)
(define keep-bound (lambda (fs bound) (if (null? fs) nil (if (mem? (car fs) bound) (cons (car fs) (keep-bound (cdr fs) bound)) (keep-bound (cdr fs) bound)))))
(define lift-list (lambda (fs bound ctr)
  (if (pair? fs)
    (let ((rh (lift (car fs) bound ctr)))
      (let ((rt (lift-list (cdr fs) bound (car (cdr (cdr rh))))))
        (list (cons (car rh) (car rt)) (append (car (cdr rh)) (car (cdr rt))) (car (cdr (cdr rt))))))
    (list fs nil ctr))))
(define lift (lambda (f bound ctr)
  (if (pair? f)
    (if (eq? (car f) (quote quote)) (list f nil ctr)
      (if (eq? (car f) (quote lambda))
        (let ((lf (car (cdr f))) (rb (lift (car (cdr (cdr f))) (append (car (cdr f)) bound) ctr)))
          (let ((cap (keep-bound (fv (car rb) lf nil) bound)) (name (string->symbol (str "__lam" (number->string (car (cdr (cdr rb))))))))
            (list (cons (quote make-closure) (cons (list (quote quote) name) cap))
                  (append (car (cdr rb)) (list (list (quote define) name (list (quote clambda) lf cap (car rb)))))
                  (+ (car (cdr (cdr rb))) 1))))
        (lift-list f bound ctr)))
    (list f nil ctr))))
(define arith? (lambda (o) (if (eq? o (quote +)) t (if (eq? o (quote -)) t (eq? o (quote *))))))
(define shop (lambda (o) (cond ((eq? o (quote +)) "+") ((eq? o (quote -)) "-") ((eq? o (quote *)) "*") (t "?"))))
(define shcmp (lambda (o) (cond ((eq? o (quote <)) "-lt") ((eq? o (quote =)) "-eq") (t "?"))))
(define pred? (lambda (o) (cond ((eq? o (quote null?)) t) ((eq? o (quote eq?)) t) ((eq? o (quote pair?)) t) ((eq? o (quote atom?)) t) ((eq? o (quote number?)) t) ((eq? o (quote string?)) t) ((eq? o (quote symbol?)) t) ((eq? o (quote <)) t) ((eq? o (quote =)) t) (t nil))))
(define builtin? (lambda (o) (cond ((eq? o (quote write-lines)) t) ((eq? o (quote append-lines)) t) ((eq? o (quote gc)) t) (t nil))))
;; primitives inlined in CALL position have no fn value; in VALUE position (e.g. (foldr + 0 xs)) they
;; compile to a C:<label> wrapper -- a fixed-arity applicative fn (src/prims.lisp, compiled into the
;; runtime) named __p_<op>. nil = not a wrappable primitive.
(define prim-wrap (lambda (s)
  (cond ((eq? s (quote +)) "__p_add") ((eq? s (quote -)) "__p_sub") ((eq? s (quote *)) "__p_mul")
        ((eq? s (quote <)) "__p_lt")  ((eq? s (quote =)) "__p_neq")
        ((eq? s (quote cons)) "__p_cons") ((eq? s (quote car)) "__p_car") ((eq? s (quote cdr)) "__p_cdr")
        ((eq? s (quote null?)) "__p_null") ((eq? s (quote eq?)) "__p_eq") ((eq? s (quote pair?)) "__p_pair")
        ((eq? s (quote not)) "__p_not")
        (t nil))))
(define bargs (lambda (refs) (if (null? refs) "" (str " " (dq) (shval (car refs)) (dq) (bargs (cdr refs))))))
(define sh-mangle-at (lambda (c) (cond ((eq? c "-") "_") ((eq? c ">") "zzG") ((eq? c "<") "zzL") ((eq? c "*") "zzS") ((eq? c "?") "zzQ") ((eq? c "!") "zzB") ((eq? c "=") "zzE") ((eq? c "+") "zzP") (t c))))
(define sh-mangle-go (lambda (s i n acc) (if (= i n) acc (sh-mangle-go s (+ i 1) n (string-append acc (sh-mangle-at (substring s i 1)))))))
(define sh-mangle (lambda (s) (sh-mangle-go s 0 (string-length s) "")))

;; ref: (lit . n) | (cst . TAGGED) | (loc . VAR)
(define shval (lambda (r) (cond ((eq? (car r) (quote lit)) (str "I:" (cdr r))) ((eq? (car r) (quote cst)) (cdr r)) (t (str "${" (cdr r) "}")))))
(define shdet (lambda (r) (cond ((eq? (car r) (quote lit)) (cdr r)) ((eq? (car r) (quote cst)) (substring (cdr r) 2 (- (string-length (cdr r)) 2))) (t (str "${" (cdr r) "#??}")))))   ; cst -> strip the 2-char tag
(define rvar (lambda (r) (if (eq? (car r) (quote loc)) (cdr r) nil)))   ; loc var name, else nil

;; builder b = (blk cur pc npc k smax). chained helpers RETURN a builder; result-producers return (b . ref).
(define b-blk (lambda (b) (car b)))      (define b-cur (lambda (b) (car (cdr b))))
(define b-pc  (lambda (b) (car (cdr (cdr b))))) (define b-npc (lambda (b) (cadddr b)))
(define b-k   (lambda (b) (car (cdr (cdr (cdr (cdr b))))))) (define b-smax (lambda (b) (car (cdr (cdr (cdr (cdr (cdr b))))))))
(define mkb (lambda (blk cur pc npc k sm) (cons blk (cons cur (cons pc (cons npc (cons k (cons sm nil))))))))
(define emit (lambda (b ln) (mkb (b-blk b) (cons ln (b-cur b)) (b-pc b) (b-npc b) (b-k b) (b-smax b))))
(define bk+ (lambda (b) (mkb (b-blk b) (b-cur b) (b-pc b) (b-npc b) (+ (b-k b) 1) (b-smax b))))
(define bsm (lambda (b n) (mkb (b-blk b) (b-cur b) (b-pc b) (b-npc b) (b-k b) (maxi (b-smax b) n))))
(define bnpc+ (lambda (b) (mkb (b-blk b) (b-cur b) (b-pc b) (+ (b-npc b) 1) (b-k b) (b-smax b))))
(define switch (lambda (b to) (mkb (cons (cons (b-pc b) (rev (b-cur b) nil)) (b-blk b)) nil to (b-npc b) (b-k b) (b-smax b))))
(define tmpn (lambda (b) (str "sht" (number->string (b-k b)))))

;; spill/unspill enclosing live locs around a call (frame slots FP+NP+j; NP set per fn)
;; bsl/eqt are FUNCTIONS, not consts: a computed const (define X (call ...)) isn't handled by the
;; per-form codegen driver (gen1 only bakes ATOM consts or lambdas) -> it would self-compile to a
;; stale heap pointer. As 0-arg fns they compile cleanly. bsl = one backslash (char 0 of "\$");
;; eqt = the 2-char sequence \" (quotes a value's RHS inside eval "...").
(define bsl (lambda () (substring "\$" 0 1)))
(define eqt (lambda () (str (bsl) (dq))))
(define fval (lambda (r) (cond ((eq? (car r) (quote loc)) (str "\${" (cdr r) "}")) ((eq? (car r) (quote lit)) (str "I:" (cdr r))) (t (cdr r)))))
;; like fval but for a DIRECT (non-eval) RHS: loc -> ${var} (no backslash), lit -> I:n, cst -> value.
(define refrhs (lambda (r) (cond ((eq? (car r) (quote loc)) (str "${" (cdr r) "}")) ((eq? (car r) (quote lit)) (str "I:" (cdr r))) (t (cdr r)))))
(define spill (lambda (b live j) (if (null? live) b (spill (emit b (str "eval " (dq) "F$((FP+NP+" (number->string j) "))=" (eqt) "\${" (car live) "}" (eqt) (dq))) (cdr live) (+ j 1)))))
(define unspill (lambda (b live j) (if (null? live) b (unspill (emit b (str "eval " (dq) (car live) "=" (eqt) "\$F$((FP+NP+" (number->string j) "))" (eqt) (dq))) (cdr live) (+ j 1)))))
;; Frame stores go through eval (dynamic slot name) -> the value is parsed TWICE (the line, then
;; the eval). A loc value (${var}) is safe (var holds the literal). A cst with a `$` (comp's
;; "$ELIDE" sentinel) is NOT: one sh-esc survives the line parse but the eval then expands it.
;; So materialise a cst into STGV by direct assignment (single level -> single sh-esc is right),
;; then store STGV as a loc (the safe path). loc/lit stage directly.
(define stage (lambda (b refs i) (if (null? refs) b (stage
  (if (eq? (car (car refs)) (quote cst))
    (emit (emit b (str "STGV=" (dq) (cdr (car refs)) (dq))) (str "eval " (dq) "F$((NFP+" (number->string i) "))=" (eqt) "\$STGV" (eqt) (dq)))
    (emit b (str "eval " (dq) "F$((NFP+" (number->string i) "))=" (eqt) (fval (car refs)) (eqt) (dq))))
  (cdr refs) (+ i 1)))))
(define setparams (lambda (b refs i) (if (null? refs) b (setparams
  (if (eq? (car (car refs)) (quote cst))
    (emit (emit b (str "STGV=" (dq) (cdr (car refs)) (dq))) (str "eval " (dq) "F$((FP+" (number->string i) "))=" (eqt) "\$STGV" (eqt) (dq)))
    (emit b (str "eval " (dq) "F$((FP+" (number->string i) "))=" (eqt) (fval (car refs)) (eqt) (dq))))
  (cdr refs) (+ i 1)))))

;; lower a list of args -> (b . refs), threading live-add so a later arg's call saves earlier temps
(define largs (lambda (es pmap b live)
  (if (null? es) (cons b nil)
    (let ((r1 (lval (car es) pmap b live)))
      (let ((vr (rvar (cdr r1))))
        (let ((rr (largs (cdr es) pmap (car r1) (if (null? vr) live (cons vr live)))))
          (cons (car rr) (cons (cdr r1) (cdr rr)))))))))

;; lval: VALUE position -> (b . ref). a non-tail CALL ends the block (yield) + opens a resume block.
(define lval (lambda (f pmap b live)
  (cond
    ((number? f) (cons b (cons (quote lit) (number->string f))))
    ((eq? f (quote nil)) (cons b (cons (quote cst) "NIL")))
    ((eq? f (quote t)) (cons b (cons (quote cst) "S:t")))
    ((string? f) (cons b (cons (quote cst) (str "T:" (sh-esc f)))))
    ((symbol? f) (let ((p (lookup f pmap)))
       (if (null? p)
         ;; pmap miss: a primitive used as a VALUE -> C:<wrapper>; a KNOWN top-level fn used as a
         ;; VALUE -> first-class C:<label> fn-value (global analog of a closure's K:<idx>); else a
         ;; global constant G_<name>.
         (if (prim-wrap f) (cons b (cons (quote cst) (str "C:" (prim-wrap f))))
           (if (mem? f (lookup (quote __gfns) pmap)) (cons b (cons (quote cst) (str "C:" (sh-mangle (symbol->string f)))))
             (cons b (cons (quote loc) (str "G_" (symbol->string f))))))
         (cons b (cons (quote loc) p)))))
    ((arith? (car f))
      (let ((ra (lval (car (cdr f)) pmap b live)))
        (let ((rb (lval (car (cdr (cdr f))) pmap (car ra) (let ((v (rvar (cdr ra)))) (if (null? v) live (cons v live))))))
          (let ((tmp (tmpn (car rb))))
            (cons (bk+ (emit (car rb) (str tmp "=" (dq) "I:$(( " (shdet (cdr ra)) " " (shop (car f)) " " (shdet (cdr rb)) " ))" (dq))))
                  (cons (quote loc) tmp))))))
    ((eq? (car f) (quote car))
      (let ((ra (lval (car (cdr f)) pmap b live)))
        (let ((tmp (tmpn (car ra))))
          (cons (bk+ (emit (emit (car ra) (str "hp_car " (dq) (shval (cdr ra)) (dq))) (str tmp "=" (dq) "${R}" (dq)))) (cons (quote loc) tmp)))))
    ((eq? (car f) (quote cdr))
      (let ((ra (lval (car (cdr f)) pmap b live)))
        (let ((tmp (tmpn (car ra))))
          (cons (bk+ (emit (emit (car ra) (str "hp_cdr " (dq) (shval (cdr ra)) (dq))) (str tmp "=" (dq) "${R}" (dq)))) (cons (quote loc) tmp)))))
    ((eq? (car f) (quote cons))
      (let ((ar (largs (cdr f) pmap b live)))
        (let ((tmp (tmpn (car ar))) (a0 (car (cdr ar))) (a1 (car (cdr (cdr ar)))))
          (cons (bk+ (bsm (emit (unspill (emit (spill (car ar) live 0) (str "hp_cons " (dq) (shval a0) (dq) " " (dq) (shval a1) (dq))) live 0)
                                (str tmp "=" (dq) "${R}" (dq))) (lenl live)))
                (cons (quote loc) tmp)))))
    ((eq? (car f) (quote quote)) (lquote (car (cdr f)) b))
    ((eq? (car f) (quote cond)) (lval (cond->if (cdr f)) pmap b live))
    ((eq? (car f) (quote and)) (lval (dsg-and (cdr f)) pmap b live))
    ((eq? (car f) (quote or)) (lval (dsg-or (cdr f)) pmap b live))
    ((eq? (car f) (quote str)) (lval (dsg-str (cdr f)) pmap b live))
    ((eq? (car f) (quote list)) (lval (dsg-list (cdr f)) pmap b live))
    ((eq? (car f) (quote when)) (lval (when->if (car (cdr f)) (cdr (cdr f))) pmap b live))
    ((eq? (car f) (quote unless)) (lval (unless->if (car (cdr f)) (cdr (cdr f))) pmap b live))
    ((eq? (car f) (quote case)) (lval (case->cond (car (cdr f)) (cdr (cdr f))) pmap b live))
    ((eq? (car f) (quote let*)) (lval (let*->lets (car (cdr f)) (cdr (cdr f))) pmap b live))
    ((eq? (car f) (quote begin)) (lbegin (cdr f) pmap b live))
    ((eq? (car f) (quote let)) (llet (car (cdr f)) (car (cdr (cdr f))) pmap b live))
    ((eq? (car f) (quote if)) (lif-val (car (cdr f)) (car (cdr (cdr f))) (cadddr f) pmap b live))
    ((eq? (car f) (quote dq)) (cons b (cons (quote loc) "G_DQ")))
    ((eq? (car f) (quote symbol->string)) (lretag f "T:" pmap b live))
    ((eq? (car f) (quote number->string)) (lretag f "T:" pmap b live))
    ((eq? (car f) (quote string->symbol)) (lretag f "S:" pmap b live))
    ((eq? (car f) (quote string->number)) (lretag f "I:" pmap b live))
    ((eq? (car f) (quote string-length))
      (let ((rx (lval (car (cdr f)) pmap b live))) (let ((tmp (tmpn (car rx))))
        (cons (bk+ (emit (car rx) (str tmp "=" (dq) "I:$(( ${#" (cdr (cdr rx)) "} - 2 ))" (dq)))) (cons (quote loc) tmp)))))
    ((eq? (car f) (quote string-append))
      (let ((ra (lval (car (cdr f)) pmap b live)))
        (let ((rb (lval (car (cdr (cdr f))) pmap (car ra) (addlive (cdr ra) live))))
          (let ((tmp (tmpn (car rb))))
            (cons (bk+ (emit (car rb) (str tmp "=" (dq) "T:" (shdet (cdr ra)) (shdet (cdr rb)) (dq)))) (cons (quote loc) tmp))))))
    ((eq? (car f) (quote substring))
      (let ((rs (lval (car (cdr f)) pmap b live)))
        (let ((ro (lval (car (cdr (cdr f))) pmap (car rs) (addlive (cdr rs) live))))
          (let ((rn (lval (cadddr f) pmap (car ro) (addlive (cdr ro) (addlive (cdr rs) live)))))
            (let ((tmp (tmpn (car rn))))
              (cons (bk+ (emit (car rn) (str tmp "=" (dq) "T:$(printf '%s' " (dq) (shdet (cdr rs)) (dq) " | cut -c$(( " (shdet (cdr ro)) " + 1 ))-$(( " (shdet (cdr ro)) " + " (shdet (cdr rn)) " )))" (dq)))) (cons (quote loc) tmp)))))))
    ((pred? (car f))
      (let ((rt (ctest f pmap b live))) (let ((tmp (tmpn (car rt))))
        (cons (bk+ (emit (emit (emit (emit (emit (car rt) (str "if " (cdr rt) "; then")) (str tmp "=" (dq) "S:t" (dq))) "else") (str tmp "=" (dq) "NIL" (dq))) "fi")) (cons (quote loc) tmp)))))
    ((builtin? (car f))
      (let ((ar (largs (cdr f) pmap b live)))
        (let ((mn (sh-mangle (symbol->string (car f)))) (tmp (tmpn (car ar))))
          (cons (bk+ (bsm (emit (unspill (emit (spill (car ar) live 0) (str mn (bargs (cdr ar)))) live 0)
                                (str tmp "=" (dq) "${R}" (dq))) (lenl live)))
                (cons (quote loc) tmp)))))
    ((eq? (car f) (quote make-closure))
      ;; (make-closure (quote __lamN) cap...) -> heap record (S:__lamN cap...) tagged K:<idx>
      (let ((rr (lval (list (quote cons) (car (cdr f)) (mkclo-caps (cdr (cdr f)))) pmap b live)))
        (let ((tmp (tmpn (car rr))))
          (cons (bk+ (emit (car rr) (str tmp "=" (dq) "K:${" (cdr (cdr rr)) "#P:}" (dq)))) (cons (quote loc) tmp)))))
    ((eq? (car f) (quote apply))
      ;; (apply fn arglist): eval fn -> CALLEE, eval arglist -> APLIST; yield ACTION=apply. The driver's
      ;; apply arm spreads APLIST into the callee frame slots (runtime count) then dispatches like a call.
      (let ((rc (lval (car (cdr f)) pmap b live)))
        (let ((live2 (addlive (cdr rc) live)))
          (let ((rl (lval (car (cdr (cdr f))) pmap (car rc) live2)))
            (let ((live3 (addlive (cdr rl) live2)) (rpc (b-npc (car rl))))
              (let ((bc (emit (emit (emit (emit (spill (bnpc+ (car rl)) live3 0) "NFP=$FTOP")
                                          (str "CALLEE=" (refrhs (cdr rc))))
                                    (str "APLIST=" (refrhs (cdr rl))))
                              (str "RPC=" (number->string rpc) "; ACTION=apply; return"))))
                (let ((br (switch bc rpc)))
                  (let ((tmp (tmpn br)))
                    (cons (bk+ (bsm (emit (unspill br live3 0) (str tmp "=" (dq) "${R}" (dq))) (lenl live3)))
                          (cons (quote loc) tmp))))))))))
    (t
      (if (if (symbol? (car f)) (null? (lookup (car f) pmap)) nil)
        ;; named call: CALLEE = the mangled global fn name
        (let ((ar (largs (cdr f) pmap b live)))
          (let ((rpc (b-npc (car ar))) (mn (sh-mangle (symbol->string (car f)))))
            (let ((bc (emit (emit (stage (emit (spill (bnpc+ (car ar)) live 0) "NFP=$FTOP") (cdr ar) 0) (str "CALLEE=" mn))
                            (str "RPC=" (number->string rpc) "; ACTION=call; return"))))
              (let ((br (switch bc rpc)))
                (let ((tmp (tmpn br)))
                  (cons (bk+ (bsm (emit (unspill br live 0) (str tmp "=" (dq) "${R}" (dq))) (lenl live)))
                        (cons (quote loc) tmp)))))))
        ;; computed call: eval the callee (a closure value) -> CALLEE=$cvar; the driver's K: case
        ;; reads the record's label into CURFN and sets CLO for captured-var loads.
        (let ((rc (lval (car f) pmap b live)))
          (let ((cvar (cdr (cdr rc))) (live2 (addlive (cdr rc) live)))
            (let ((ar (largs (cdr f) pmap (car rc) live2)))
              (let ((rpc (b-npc (car ar))))
                (let ((bc (emit (emit (stage (emit (spill (bnpc+ (car ar)) live2 0) "NFP=$FTOP") (cdr ar) 0) (str "CALLEE=${" cvar "}"))
                                (str "RPC=" (number->string rpc) "; ACTION=call; return"))))
                  (let ((br (switch bc rpc)))
                    (let ((tmp (tmpn br)))
                      (cons (bk+ (bsm (emit (unspill br live2 0) (str tmp "=" (dq) "${R}" (dq))) (lenl live2)))
                            (cons (quote loc) tmp))))))))))))))

;; sh-esc: escape a string literal for a double-quoted sh assignment (STGV="<...>"). Both \ and $
;; must be escaped -- \ -> \\ and $ -> \$ -- else a `\$` sequence (deferred-expansion templates
;; like \$F$((FP+..)) collapses: the \ is eaten and $F expands. Char-scan (mirrors sh-mangle-go),
;; comp-inlined prims only (NOT `split`, which compiled code can't call). `bs` yields one backslash
;; (carved from "\$") since a literal "\" string + a (define X (substring ...)) const are awkward.
;; comp.sh never exercised the \ case (cmd emits no \$); the native sh-emitter does -> this matters.
(define sh-esc-at (lambda (c) (if (eq? c "$") "\$" (if (eq? c (bsl)) (string-append (bsl) (bsl)) c))))
(define sh-esc-go (lambda (s i n acc) (if (= i n) acc (sh-esc-go s (+ i 1) n (string-append acc (sh-esc-at (substring s i 1)))))))
(define sh-esc (lambda (s) (sh-esc-go s 0 (string-length s) "")))
(define dsg-str  (lambda (es) (if (null? es) "" (if (null? (cdr es)) (car es) (list (quote string-append) (car es) (dsg-str (cdr es)))))))
(define dsg-list (lambda (es) (if (null? es) (quote nil) (list (quote cons) (car es) (dsg-list (cdr es))))))
(define dsg-and  (lambda (es) (if (null? es) (quote t)   (if (null? (cdr es)) (car es) (list (quote if) (car es) (dsg-and (cdr es)) (quote nil))))))
;; or: single-eval via a __or temp (NOT (if x x ...) which double-evaluates x). __or reserved.
(define dsg-or   (lambda (es) (if (null? es) (quote nil) (if (null? (cdr es)) (car es) (list (quote let) (list (list (quote __or) (car es))) (list (quote if) (quote __or) (quote __or) (dsg-or (cdr es))))))))
;; cond->if: clause body is a SEQUENCE -> (begin body...) (single-expr begin collapses in codegen).
(define cond->if (lambda (cl) (if (null? cl) (quote nil) (let ((c (car cl))) (if (eq? (car c) (quote t)) (cons (quote begin) (cdr c)) (list (quote if) (car c) (cons (quote begin) (cdr c)) (cond->if (cdr cl))))))))
(define when->if (lambda (c body) (list (quote if) c (cons (quote begin) body) (quote nil))))
(define unless->if (lambda (c body) (list (quote if) c (quote nil) (cons (quote begin) body))))
(define case-clause (lambda (cl)
  (if (eq? (car cl) (quote else)) (cons (quote t) (cdr cl))
    (cons (list (quote eq?) (quote __case) (list (quote quote) (car cl))) (cdr cl)))))
(define case-clauses (lambda (cls) (if (null? cls) nil (cons (case-clause (car cls)) (case-clauses (cdr cls))))))
(define case->cond (lambda (key clauses)
  (list (quote let) (list (list (quote __case) key)) (cons (quote cond) (case-clauses clauses)))))
(define let*->lets (lambda (binds body)
  (if (null? binds) (cons (quote begin) body)
    (list (quote let) (list (car binds)) (let*->lets (cdr binds) body)))))
(define lquote (lambda (d b) (cond ((null? d) (cons b (cons (quote cst) "NIL"))) ((number? d) (cons b (cons (quote lit) (number->string d)))) ((string? d) (cons b (cons (quote cst) (str "T:" (sh-esc d))))) ((symbol? d) (cons b (cons (quote cst) (str "S:" (sh-esc (symbol->string d)))))) (t (lval (list (quote cons) (list (quote quote) (car d)) (list (quote quote) (cdr d))) nil b nil)))))
(define lbegin (lambda (es pmap b live) (if (null? (cdr es)) (lval (car es) pmap b live) (let ((r1 (lval (car es) pmap b live))) (lbegin (cdr es) pmap (car r1) live)))))
(define lbinds (lambda (binds pmap b live) (if (null? binds) (list b pmap live) (let ((r1 (lval (car (cdr (car binds))) pmap b live))) (let ((tmp (tmpn (car r1)))) (lbinds (cdr binds) (cons (cons (car (car binds)) tmp) pmap) (bk+ (emit (car r1) (str tmp "=" (dq) (shval (cdr r1)) (dq)))) (cons tmp live)))))))
(define llet (lambda (binds body pmap b live) (let ((r (lbinds binds pmap b live))) (lval body (car (cdr r)) (car r) (car (cdr (cdr r)))))))
(define lif-val (lambda (c a bb pmap b live)
  (let ((ct (ctest c pmap b live)))
    (let ((aid (b-npc (car ct))) (bid (+ (b-npc (car ct)) 1)) (jid (+ (b-npc (car ct)) 2)))
      (let ((tmp (tmpn (car ct))))
        (let ((b2 (emit (emit (bk+ (bnpc+ (bnpc+ (bnpc+ (car ct))))) (str "if " (cdr ct) "; then PC=" (number->string aid) "; else PC=" (number->string bid) "; fi")) "ACTION=jump; return")))
          (let ((ra (lval a pmap (switch b2 aid) live)))
            (let ((ba (emit (emit (car ra) (str tmp "=" (dq) (shval (cdr ra)) (dq))) (str "PC=" (number->string jid) "; ACTION=jump; return"))))
              (let ((rb (lval bb pmap (switch ba bid) live)))
                (let ((bj (emit (emit (car rb) (str tmp "=" (dq) (shval (cdr rb)) (dq))) (str "PC=" (number->string jid) "; ACTION=jump; return"))))
                  (cons (switch bj jid) (cons (quote loc) tmp))))))))))))
(define ltbegin (lambda (es pmap fname np b live) (if (null? (cdr es)) (ltail (car es) pmap fname np b live) (let ((r1 (lval (car es) pmap b live))) (ltbegin (cdr es) pmap fname np (car r1) live)))))
(define tagtest   (lambda (r tag) (str "[ " (dq) "${" (cdr r) "#" tag "}" (dq) " != " (dq) (shval r) (dq) " ]")))
(define natagtest (lambda (r tag) (str "[ " (dq) "${" (cdr r) "#" tag "}" (dq) " = " (dq) (shval r) (dq) " ]")))
(define addlive (lambda (r live) (let ((v (rvar r))) (if (null? v) live (cons v live)))))
(define lretag (lambda (f newtag pmap b live) (let ((rx (lval (car (cdr f)) pmap b live))) (let ((tmp (tmpn (car rx)))) (cons (bk+ (emit (car rx) (str tmp "=" (dq) newtag (shdet (cdr rx)) (dq)))) (cons (quote loc) tmp))))))
;; ctest: if-test -> (b . condstr)
(define ctest (lambda (f pmap b live)
  (if (if (pair? f) (pred? (car f)) nil)
  (cond
    ((eq? (car f) (quote null?)) (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (str "[ " (dq) (shval (cdr ra)) (dq) " = NIL ]"))))
    ((eq? (car f) (quote eq?))
      (let ((ra (lval (car (cdr f)) pmap b live)))
        (let ((rb (lval (car (cdr (cdr f))) pmap (car ra) live)))
          (cons (car rb) (str "[ " (dq) (shval (cdr ra)) (dq) " = " (dq) (shval (cdr rb)) (dq) " ]")))))
    ((eq? (car f) (quote pair?))   (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (tagtest   (cdr ra) "P:"))))
    ((eq? (car f) (quote atom?))   (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (natagtest (cdr ra) "P:"))))
    ((eq? (car f) (quote number?)) (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (tagtest   (cdr ra) "I:"))))
    ((eq? (car f) (quote string?)) (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (tagtest   (cdr ra) "T:"))))
    ((eq? (car f) (quote symbol?)) (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (tagtest   (cdr ra) "S:"))))
    (t (let ((ra (lval (car (cdr f)) pmap b live)))
         (let ((rb (lval (car (cdr (cdr f))) pmap (car ra) live)))
           (cons (car rb) (str "[ " (shdet (cdr ra)) " " (shcmp (car f)) " " (shdet (cdr rb)) " ]"))))))
    ;; non-predicate test (bare var, general call, inlined if): eval -> truthiness
    (let ((rx (lval f pmap b live)))
      (cons (car rx) (str "[ " (dq) (shval (cdr rx)) (dq) " != NIL ]"))))))

;; ltail: TAIL position -> b (each path terminates)
(define ltail (lambda (f pmap fname np b live)
  (cond
    ((if (pair? f) (eq? (car f) (quote if)) nil)
      (let ((ct (ctest (car (cdr f)) pmap b live)))
        (let ((aid (b-npc (car ct))))
          (let ((bid (+ aid 1)))
            (let ((b3 (emit (emit (bnpc+ (bnpc+ (car ct))) (str "if " (cdr ct) "; then PC=" (number->string aid) "; else PC=" (number->string bid) "; fi")) "ACTION=jump; return")))
              (let ((ba (ltail (car (cdr (cdr f))) pmap fname np (switch b3 aid) live)))
                (ltail (cadddr f) pmap fname np (switch ba bid) live)))))))
    ((if (pair? f) (eq? (car f) (quote cond)) nil) (ltail (cond->if (cdr f)) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote and)) nil) (ltail (dsg-and (cdr f)) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote or)) nil) (ltail (dsg-or (cdr f)) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote str)) nil) (ltail (dsg-str (cdr f)) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote list)) nil) (ltail (dsg-list (cdr f)) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote when)) nil) (ltail (when->if (car (cdr f)) (cdr (cdr f))) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote unless)) nil) (ltail (unless->if (car (cdr f)) (cdr (cdr f))) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote case)) nil) (ltail (case->cond (car (cdr f)) (cdr (cdr f))) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote let*)) nil) (ltail (let*->lets (car (cdr f)) (cdr (cdr f))) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote begin)) nil) (ltbegin (cdr f) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote let)) nil) (let ((r (lbinds (car (cdr f)) pmap b live))) (ltail (car (cdr (cdr f))) (car (cdr r)) fname np (car r) (car (cdr (cdr r))))))
    ((if (pair? f) (eq? (car f) fname) nil)
      (let ((ar (largs (cdr f) pmap b live)))
        (emit (setparams (car ar) (cdr ar) 0) "PC=0; ACTION=tail; return")))
    (t (let ((r (lval f pmap b live)))
         (emit (car r) (str "R=" (dq) (shval (cdr r)) (dq) "; ACTION=ret; return")))))))

;; assembly
(define pmap-fr (lambda (fs i) (if (null? fs) nil (cons (cons (car fs) (str "p" (number->string i))) (pmap-fr (cdr fs) (+ i 1))))))
(define ploads (lambda (fs i) (if (null? fs) nil (cons (str "eval " (dq) "p" (number->string i) "=" (eqt) "\$F$((FP+" (number->string i) "))" (eqt) (dq)) (ploads (cdr fs) (+ i 1))))))
(define blkget (lambda (al pc) (if (null? al) nil (if (eq? (car (car al)) pc) (cdr (car al)) (blkget (cdr al) pc)))))
(define caseblocks (lambda (al i n) (if (= i n) nil (append (cons (str (number->string i) ")") (append (blkget al i) (list ";;"))) (caseblocks al (+ i 1) n)))))

(define mkclo-caps (lambda (caps) (if (null? caps) (quote nil) (list (quote cons) (car caps) (mkclo-caps (cdr caps))))))
;; cap-loads: walk the closure record (cdr is the captured list) into p<np>.. local vars.
(define cap-loads-go (lambda (cap i)
  (if (null? cap) nil
    (append (list (str "hp_car " (dq) "${_cl}" (dq)) (str "p" (number->string i) "=" (dq) "${R}" (dq)) (str "hp_cdr " (dq) "${_cl}" (dq)) (str "_cl=" (dq) "${R}" (dq)))
            (cap-loads-go (cdr cap) (+ i 1))))))
(define cap-loads (lambda (cap np)
  (if (null? cap) nil (cons (str "hp_cdr " (dq) "P:${CLO}" (dq)) (cons (str "_cl=" (dq) "${R}" (dq)) (cap-loads-go cap np))))))
;; a lifted closure sub: formals from frame slots, captured vars from the record (via CLO).
(define compile-clambda (lambda (name lf cap body gfns)
  (let ((np (lenl lf)) (pm (cons (cons (quote __gfns) gfns) (pmap-fr (append lf cap) 0))) (mn (sh-mangle (symbol->string name))))
    (let ((bf (ltail body pm name np (mkb nil nil 0 1 0 0) nil)))
      (let ((blk (cons (cons (b-pc bf) (rev (b-cur bf) nil)) (b-blk bf))) (fsz (+ np (b-smax bf))))
        (append (cons (str "SIZE_" mn "=" (number->string fsz))
                  (cons (str mn "() {")
                    (append (ploads lf 0)
                      (append (cap-loads cap np)
                        (cons (str "FTOP=$((FP + SIZE_" mn "))")
                          (cons (str "NP=" (number->string np)) (cons "case $PC in" (caseblocks blk 0 (b-npc bf)))))))))
                (list "esac; }")))))))
;; lambda-lift the whole program: hoist inline lambdas in each define's body, emitting the
;; transformed define + the lifted closure-sub defines (interleaved). ctr threads fresh names.
(define lift-program (lambda (forms ctr)
  (if (null? forms) nil
    (let ((d (car forms)))
      (if (if (pair? d) (if (eq? (car d) (quote define)) (if (pair? (car (cdr (cdr d)))) (eq? (car (car (cdr (cdr d)))) (quote lambda)) nil) nil) nil)
        (let ((nm (car (cdr d))) (lf (car (cdr (car (cdr (cdr d)))))) (bd (car (cdr (cdr (car (cdr (cdr d))))))))
          (let ((r (lift bd lf ctr)))
            (cons (list (quote define) nm (list (quote lambda) lf (car r)))
                  (append (car (cdr r)) (lift-program (cdr forms) (car (cdr (cdr r))))))))
        (cons d (lift-program (cdr forms) ctr)))))))
(define compile-fn-bb (lambda (name params body gfns)
  (let ((np (lenl params)) (pm (cons (cons (quote __gfns) gfns) (pmap-fr params 0))) (mn (sh-mangle (symbol->string name))))
    (let ((bf (ltail body pm name np (mkb nil nil 0 1 0 0) nil)))
      (let ((blk (cons (cons (b-pc bf) (rev (b-cur bf) nil)) (b-blk bf))) (fsz (+ np (b-smax bf))))
        (append (cons (str "SIZE_" mn "=" (number->string fsz))
                  (cons (str mn "() {")
                    (append (ploads params 0)
                      (cons (str "FTOP=$((FP + SIZE_" mn "))")
                        (cons (str "NP=" (number->string np)) (cons "case $PC in" (caseblocks blk 0 (b-npc bf))))))))
                (list "esac; }")))))))
(define compile-def-sh (lambda (d gfns)
  (if (if (pair? (car (cdr (cdr d)))) (eq? (car (car (cdr (cdr d)))) (quote clambda)) nil)
    (compile-clambda (car (cdr d)) (car (cdr (car (cdr (cdr d))))) (car (cdr (cdr (car (cdr (cdr d)))))) (car (cdr (cdr (cdr (car (cdr (cdr d))))))) gfns)
    (compile-fn-bb (car (cdr d)) (car (cdr (car (cdr (cdr d))))) (car (cdr (cdr (car (cdr (cdr d)))))) gfns))))
;; gfn-names: top-level fn names (defines whose body is a lambda) -> the known-fns set; a
;; reference to one of these in VALUE position compiles to a C:<label> first-class fn-value.
(define gfn-names (lambda (forms)
  (if (null? forms) nil
    (let ((d (car forms)))
      (if (if (pair? (car (cdr (cdr d)))) (eq? (car (car (cdr (cdr d)))) (quote lambda)) nil)
        (cons (car (cdr d)) (gfn-names (cdr forms)))
        (gfn-names (cdr forms)))))))
;; whole-program entry (for the native sh-emitter, comp-sh.sh): lambda-lift, then per top-level
;; form emit either a compiled fn (lambda/clambda body) or a G_<name> constant init (atom body),
;; concatenated. Mirrors tools/bootstrap-comp.sh's gen1 but over the whole program in one process.
(define cval-sh (lambda (v) (cond ((string? v) (str "T:" v)) ((number? v) (str "I:" (number->string v))) (t (str "S:" (symbol->string v))))))
(define gen1-sh (lambda (f gfns)
  (if (pair? (car (cdr (cdr f)))) (compile-def-sh f gfns)
    (list (str "G_" (symbol->string (car (cdr f))) "='" (cval-sh (car (cdr (cdr f)))) "'")))))
(define compile-all-sh (lambda (fs gfns) (if (null? fs) nil (append (gen1-sh (car fs) gfns) (compile-all-sh (cdr fs) gfns)))))
(define compile-program-sh (lambda (forms outpath)
  (let ((lifted (lift-program forms 0))) (write-lines outpath (compile-all-sh lifted (gfn-names lifted))))))
