;;; compile-sh.lisp -- Lisp->sh backend, TRAMPOLINE codegen (basic-block lowering).
;;; Each fn becomes a resumable segment-machine dispatched by a driver loop (build-comp.sh):
;;; host stack depth stays 2 regardless of logical recursion depth. Live data lives in the
;;; frame stack F[0..FP+SIZE_fn); gc_run scans it. Replaces the old direct-call frame-mirror.
;; ===== trampoline codegen (dev) — basic-block lowering. chained-emit style (low nesting). =====
(define cadddr (lambda (x) (car (cdr (cdr (cdr x))))))
(define rev (lambda (xs acc) (if (null? xs) acc (rev (cdr xs) (cons (car xs) acc)))))
(define lookup (lambda (k al) (if (null? al) nil (if (eq? (car (car al)) k) (cdr (car al)) (lookup k (cdr al))))))
(define lenl (lambda (xs) (if (null? xs) 0 (+ 1 (lenl (cdr xs))))))
(define maxi (lambda (a b) (if (< a b) b a)))
(define append (lambda (a b) (if (null? a) b (cons (car a) (append (cdr a) b)))))
(define arith? (lambda (o) (if (eq? o (quote +)) t (if (eq? o (quote -)) t (eq? o (quote *))))))
(define shop (lambda (o) (cond ((eq? o (quote +)) "+") ((eq? o (quote -)) "-") ((eq? o (quote *)) "*") (t "?"))))
(define shcmp (lambda (o) (cond ((eq? o (quote <)) "-lt") ((eq? o (quote =)) "-eq") (t "?"))))
(define pred? (lambda (o) (cond ((eq? o (quote null?)) t) ((eq? o (quote eq?)) t) ((eq? o (quote pair?)) t) ((eq? o (quote atom?)) t) ((eq? o (quote number?)) t) ((eq? o (quote string?)) t) ((eq? o (quote symbol?)) t) ((eq? o (quote <)) t) ((eq? o (quote =)) t) (t nil))))
(define builtin? (lambda (o) (cond ((eq? o (quote write-lines)) t) ((eq? o (quote append-lines)) t) ((eq? o (quote gc)) t) (t nil))))
(define bargs (lambda (refs) (if (null? refs) "" (str " " (dq) (shval (car refs)) (dq) (bargs (cdr refs))))))
(define sh-mangle-at (lambda (c) (cond ((eq? c "-") "_") ((eq? c ">") "zzG") ((eq? c "<") "zzL") ((eq? c "*") "zzS") ((eq? c "?") "zzQ") ((eq? c "!") "zzB") ((eq? c "=") "zzE") ((eq? c "+") "zzP") (t c))))
(define sh-mangle-go (lambda (s i n acc) (if (= i n) acc (sh-mangle-go s (+ i 1) n (string-append acc (sh-mangle-at (substring s i 1)))))))
(define sh-mangle (lambda (s) (sh-mangle-go s 0 (string-length s) "")))

;; ref: (lit . n) | (cst . TAGGED) | (loc . VAR)
(define shval (lambda (r) (cond ((eq? (car r) (quote lit)) (str "I:" (cdr r))) ((eq? (car r) (quote cst)) (cdr r)) (t (str "${" (cdr r) "}")))))
(define shdet (lambda (r) (cond ((eq? (car r) (quote lit)) (cdr r)) ((eq? (car r) (quote cst)) (substring (cdr r) 2 (- (string-length (cdr r)) 2))) (t (str "${" (cdr r) "#??}")))))   ; cst -> strip the 2-char tag
(define rvar (lambda (r) (if (eq? (car r) (quote loc)) (cdr r) nil)))   ; loc var name, else nil

;; builder b = (blk cur pc npc k smax). chained helpers RETURN a builder; result-producers return (b . ref).
(define b-blk (lambda (b) (car b)))      (define b-cur (lambda (b) (car (cdr b))))
(define b-pc  (lambda (b) (car (cdr (cdr b))))) (define b-npc (lambda (b) (cadddr b)))
(define b-k   (lambda (b) (car (cdr (cdr (cdr (cdr b))))))) (define b-smax (lambda (b) (car (cdr (cdr (cdr (cdr (cdr b))))))))
(define mkb (lambda (blk cur pc npc k sm) (cons blk (cons cur (cons pc (cons npc (cons k (cons sm nil))))))))
(define emit (lambda (b ln) (mkb (b-blk b) (cons ln (b-cur b)) (b-pc b) (b-npc b) (b-k b) (b-smax b))))
(define bk+ (lambda (b) (mkb (b-blk b) (b-cur b) (b-pc b) (b-npc b) (+ (b-k b) 1) (b-smax b))))
(define bsm (lambda (b n) (mkb (b-blk b) (b-cur b) (b-pc b) (b-npc b) (b-k b) (maxi (b-smax b) n))))
(define bnpc+ (lambda (b) (mkb (b-blk b) (b-cur b) (b-pc b) (+ (b-npc b) 1) (b-k b) (b-smax b))))
(define switch (lambda (b to) (mkb (cons (cons (b-pc b) (rev (b-cur b) nil)) (b-blk b)) nil to (b-npc b) (b-k b) (b-smax b))))
(define tmpn (lambda (b) (str "sht" (number->string (b-k b)))))

;; spill/unspill enclosing live locs around a call (frame slots FP+NP+j; NP set per fn)
(define BSL (substring "\$" 0 1))   ; one literal backslash (char 0 of the 2-char string "\$")
(define EQT (str BSL (dq)))           ; the 2-char sequence  \"  -- quotes a value's RHS *inside* eval "..."
(define fval (lambda (r) (cond ((eq? (car r) (quote loc)) (str "\${" (cdr r) "}")) ((eq? (car r) (quote lit)) (str "I:" (cdr r))) (t (cdr r)))))
(define spill (lambda (b live j) (if (null? live) b (spill (emit b (str "eval " (dq) "F$((FP+NP+" (number->string j) "))=" EQT "\${" (car live) "}" EQT (dq))) (cdr live) (+ j 1)))))
(define unspill (lambda (b live j) (if (null? live) b (unspill (emit b (str "eval " (dq) (car live) "=" EQT "\$F$((FP+NP+" (number->string j) "))" EQT (dq))) (cdr live) (+ j 1)))))
;; Frame stores go through eval (dynamic slot name) -> the value is parsed TWICE (the line, then
;; the eval). A loc value (${var}) is safe (var holds the literal). A cst with a `$` (comp's
;; "$ELIDE" sentinel) is NOT: one sh-esc survives the line parse but the eval then expands it.
;; So materialise a cst into STGV by direct assignment (single level -> single sh-esc is right),
;; then store STGV as a loc (the safe path). loc/lit stage directly.
(define stage (lambda (b refs i) (if (null? refs) b (stage
  (if (eq? (car (car refs)) (quote cst))
    (emit (emit b (str "STGV=" (dq) (cdr (car refs)) (dq))) (str "eval " (dq) "F$((NFP+" (number->string i) "))=" EQT "\$STGV" EQT (dq)))
    (emit b (str "eval " (dq) "F$((NFP+" (number->string i) "))=" EQT (fval (car refs)) EQT (dq))))
  (cdr refs) (+ i 1)))))
(define setparams (lambda (b refs i) (if (null? refs) b (setparams
  (if (eq? (car (car refs)) (quote cst))
    (emit (emit b (str "STGV=" (dq) (cdr (car refs)) (dq))) (str "eval " (dq) "F$((FP+" (number->string i) "))=" EQT "\$STGV" EQT (dq)))
    (emit b (str "eval " (dq) "F$((FP+" (number->string i) "))=" EQT (fval (car refs)) EQT (dq))))
  (cdr refs) (+ i 1)))))

;; lower a list of args -> (b . refs), threading live-add so a later arg's call saves earlier temps
(define largs (lambda (es pmap b live)
  (if (null? es) (cons b nil)
    (let ((r1 (lval (car es) pmap b live)))
      (let ((vr (rvar (cdr r1))))
        (let ((rr (largs (cdr es) pmap (car r1) (if (null? vr) live (cons vr live)))))
          (cons (car rr) (cons (cdr r1) (cdr rr)))))))))

;; lval: VALUE position -> (b . ref). a non-tail CALL ends the block (yield) + opens a resume block.
(define lval (lambda (f pmap b live)
  (cond
    ((number? f) (cons b (cons (quote lit) (number->string f))))
    ((eq? f (quote nil)) (cons b (cons (quote cst) "NIL")))
    ((eq? f (quote t)) (cons b (cons (quote cst) "S:t")))
    ((string? f) (cons b (cons (quote cst) (str "T:" (sh-esc f)))))
    ((symbol? f) (let ((p (lookup f pmap))) (if (null? p) (cons b (cons (quote loc) (str "G_" (symbol->string f)))) (cons b (cons (quote loc) p)))))   ; pmap miss -> global constant G_<name>
    ((arith? (car f))
      (let ((ra (lval (car (cdr f)) pmap b live)))
        (let ((rb (lval (car (cdr (cdr f))) pmap (car ra) (let ((v (rvar (cdr ra)))) (if (null? v) live (cons v live))))))
          (let ((tmp (tmpn (car rb))))
            (cons (bk+ (emit (car rb) (str tmp "=" (dq) "I:$(( " (shdet (cdr ra)) " " (shop (car f)) " " (shdet (cdr rb)) " ))" (dq))))
                  (cons (quote loc) tmp))))))
    ((eq? (car f) (quote car))
      (let ((ra (lval (car (cdr f)) pmap b live)))
        (let ((tmp (tmpn (car ra))))
          (cons (bk+ (emit (emit (car ra) (str "hp_car " (dq) (shval (cdr ra)) (dq))) (str tmp "=" (dq) "${R}" (dq)))) (cons (quote loc) tmp)))))
    ((eq? (car f) (quote cdr))
      (let ((ra (lval (car (cdr f)) pmap b live)))
        (let ((tmp (tmpn (car ra))))
          (cons (bk+ (emit (emit (car ra) (str "hp_cdr " (dq) (shval (cdr ra)) (dq))) (str tmp "=" (dq) "${R}" (dq)))) (cons (quote loc) tmp)))))
    ((eq? (car f) (quote cons))
      (let ((ar (largs (cdr f) pmap b live)))
        (let ((tmp (tmpn (car ar))) (a0 (car (cdr ar))) (a1 (car (cdr (cdr ar)))))
          (cons (bk+ (bsm (emit (unspill (emit (spill (car ar) live 0) (str "hp_cons " (dq) (shval a0) (dq) " " (dq) (shval a1) (dq))) live 0)
                                (str tmp "=" (dq) "${R}" (dq))) (lenl live)))
                (cons (quote loc) tmp)))))
    ((eq? (car f) (quote quote)) (lquote (car (cdr f)) b))
    ((eq? (car f) (quote cond)) (lval (cond->if (cdr f)) pmap b live))
    ((eq? (car f) (quote and)) (lval (dsg-and (cdr f)) pmap b live))
    ((eq? (car f) (quote or)) (lval (dsg-or (cdr f)) pmap b live))
    ((eq? (car f) (quote str)) (lval (dsg-str (cdr f)) pmap b live))
    ((eq? (car f) (quote list)) (lval (dsg-list (cdr f)) pmap b live))
    ((eq? (car f) (quote begin)) (lbegin (cdr f) pmap b live))
    ((eq? (car f) (quote let)) (llet (car (cdr f)) (car (cdr (cdr f))) pmap b live))
    ((eq? (car f) (quote if)) (lif-val (car (cdr f)) (car (cdr (cdr f))) (cadddr f) pmap b live))
    ((eq? (car f) (quote dq)) (cons b (cons (quote loc) "G_DQ")))
    ((eq? (car f) (quote symbol->string)) (lretag f "T:" pmap b live))
    ((eq? (car f) (quote number->string)) (lretag f "T:" pmap b live))
    ((eq? (car f) (quote string->symbol)) (lretag f "S:" pmap b live))
    ((eq? (car f) (quote string->number)) (lretag f "I:" pmap b live))
    ((eq? (car f) (quote string-length))
      (let ((rx (lval (car (cdr f)) pmap b live))) (let ((tmp (tmpn (car rx))))
        (cons (bk+ (emit (car rx) (str tmp "=" (dq) "I:$(( ${#" (cdr (cdr rx)) "} - 2 ))" (dq)))) (cons (quote loc) tmp)))))
    ((eq? (car f) (quote string-append))
      (let ((ra (lval (car (cdr f)) pmap b live)))
        (let ((rb (lval (car (cdr (cdr f))) pmap (car ra) (addlive (cdr ra) live))))
          (let ((tmp (tmpn (car rb))))
            (cons (bk+ (emit (car rb) (str tmp "=" (dq) "T:" (shdet (cdr ra)) (shdet (cdr rb)) (dq)))) (cons (quote loc) tmp))))))
    ((eq? (car f) (quote substring))
      (let ((rs (lval (car (cdr f)) pmap b live)))
        (let ((ro (lval (car (cdr (cdr f))) pmap (car rs) (addlive (cdr rs) live))))
          (let ((rn (lval (cadddr f) pmap (car ro) (addlive (cdr ro) (addlive (cdr rs) live)))))
            (let ((tmp (tmpn (car rn))))
              (cons (bk+ (emit (car rn) (str tmp "=" (dq) "T:$(printf '%s' " (dq) (shdet (cdr rs)) (dq) " | cut -c$(( " (shdet (cdr ro)) " + 1 ))-$(( " (shdet (cdr ro)) " + " (shdet (cdr rn)) " )))" (dq)))) (cons (quote loc) tmp)))))))
    ((pred? (car f))
      (let ((rt (ctest f pmap b live))) (let ((tmp (tmpn (car rt))))
        (cons (bk+ (emit (emit (emit (emit (emit (car rt) (str "if " (cdr rt) "; then")) (str tmp "=" (dq) "S:t" (dq))) "else") (str tmp "=" (dq) "NIL" (dq))) "fi")) (cons (quote loc) tmp)))))
    ((builtin? (car f))
      (let ((ar (largs (cdr f) pmap b live)))
        (let ((mn (sh-mangle (symbol->string (car f)))) (tmp (tmpn (car ar))))
          (cons (bk+ (bsm (emit (unspill (emit (spill (car ar) live 0) (str mn (bargs (cdr ar)))) live 0)
                                (str tmp "=" (dq) "${R}" (dq))) (lenl live)))
                (cons (quote loc) tmp)))))
    (t
      (let ((ar (largs (cdr f) pmap b live)))
        (let ((rpc (b-npc (car ar))) (mn (sh-mangle (symbol->string (car f)))))
          (let ((bc (emit (emit (stage (emit (spill (bnpc+ (car ar)) live 0) "NFP=$FTOP") (cdr ar) 0) (str "CALLEE=" mn))
                          (str "RPC=" (number->string rpc) "; ACTION=call; return"))))
            (let ((br (switch bc rpc)))
              (let ((tmp (tmpn br)))
                (cons (bk+ (bsm (emit (unspill br live 0) (str tmp "=" (dq) "${R}" (dq))) (lenl live)))
                      (cons (quote loc) tmp)))))))))))

(define sh-esc-join (lambda (ps) (if (null? (cdr ps)) (car ps) (string-append (car ps) (string-append "\$" (sh-esc-join (cdr ps)))))))
(define sh-esc (lambda (s) (sh-esc-join (split s "$"))))
(define dsg-str  (lambda (es) (if (null? es) "" (if (null? (cdr es)) (car es) (list (quote string-append) (car es) (dsg-str (cdr es)))))))
(define dsg-list (lambda (es) (if (null? es) (quote nil) (list (quote cons) (car es) (dsg-list (cdr es))))))
(define dsg-and  (lambda (es) (if (null? es) (quote t)   (if (null? (cdr es)) (car es) (list (quote if) (car es) (dsg-and (cdr es)) (quote nil))))))
(define dsg-or   (lambda (es) (if (null? es) (quote nil) (if (null? (cdr es)) (car es) (list (quote if) (car es) (car es) (dsg-or (cdr es)))))))
(define cond->if (lambda (cl) (if (null? cl) (quote nil) (let ((c (car cl))) (if (eq? (car c) (quote t)) (car (cdr c)) (list (quote if) (car c) (car (cdr c)) (cond->if (cdr cl))))))))
(define lquote (lambda (d b) (cond ((null? d) (cons b (cons (quote cst) "NIL"))) ((number? d) (cons b (cons (quote lit) (number->string d)))) ((string? d) (cons b (cons (quote cst) (str "T:" (sh-esc d))))) ((symbol? d) (cons b (cons (quote cst) (str "S:" (sh-esc (symbol->string d)))))) (t (lval (list (quote cons) (list (quote quote) (car d)) (list (quote quote) (cdr d))) nil b nil)))))
(define lbegin (lambda (es pmap b live) (if (null? (cdr es)) (lval (car es) pmap b live) (let ((r1 (lval (car es) pmap b live))) (lbegin (cdr es) pmap (car r1) live)))))
(define lbinds (lambda (binds pmap b live) (if (null? binds) (list b pmap live) (let ((r1 (lval (car (cdr (car binds))) pmap b live))) (let ((tmp (tmpn (car r1)))) (lbinds (cdr binds) (cons (cons (car (car binds)) tmp) pmap) (bk+ (emit (car r1) (str tmp "=" (dq) (shval (cdr r1)) (dq)))) (cons tmp live)))))))
(define llet (lambda (binds body pmap b live) (let ((r (lbinds binds pmap b live))) (lval body (car (cdr r)) (car r) (car (cdr (cdr r)))))))
(define lif-val (lambda (c a bb pmap b live)
  (let ((ct (ctest c pmap b live)))
    (let ((aid (b-npc (car ct))) (bid (+ (b-npc (car ct)) 1)) (jid (+ (b-npc (car ct)) 2)))
      (let ((tmp (tmpn (car ct))))
        (let ((b2 (emit (emit (bk+ (bnpc+ (bnpc+ (bnpc+ (car ct))))) (str "if " (cdr ct) "; then PC=" (number->string aid) "; else PC=" (number->string bid) "; fi")) "ACTION=jump; return")))
          (let ((ra (lval a pmap (switch b2 aid) live)))
            (let ((ba (emit (emit (car ra) (str tmp "=" (dq) (shval (cdr ra)) (dq))) (str "PC=" (number->string jid) "; ACTION=jump; return"))))
              (let ((rb (lval bb pmap (switch ba bid) live)))
                (let ((bj (emit (emit (car rb) (str tmp "=" (dq) (shval (cdr rb)) (dq))) (str "PC=" (number->string jid) "; ACTION=jump; return"))))
                  (cons (switch bj jid) (cons (quote loc) tmp))))))))))))
(define ltbegin (lambda (es pmap fname np b live) (if (null? (cdr es)) (ltail (car es) pmap fname np b live) (let ((r1 (lval (car es) pmap b live))) (ltbegin (cdr es) pmap fname np (car r1) live)))))
(define tagtest   (lambda (r tag) (str "[ " (dq) "${" (cdr r) "#" tag "}" (dq) " != " (dq) (shval r) (dq) " ]")))
(define natagtest (lambda (r tag) (str "[ " (dq) "${" (cdr r) "#" tag "}" (dq) " = " (dq) (shval r) (dq) " ]")))
(define addlive (lambda (r live) (let ((v (rvar r))) (if (null? v) live (cons v live)))))
(define lretag (lambda (f newtag pmap b live) (let ((rx (lval (car (cdr f)) pmap b live))) (let ((tmp (tmpn (car rx)))) (cons (bk+ (emit (car rx) (str tmp "=" (dq) newtag (shdet (cdr rx)) (dq)))) (cons (quote loc) tmp))))))
;; ctest: if-test -> (b . condstr)
(define ctest (lambda (f pmap b live)
  (if (if (pair? f) (pred? (car f)) nil)
  (cond
    ((eq? (car f) (quote null?)) (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (str "[ " (dq) (shval (cdr ra)) (dq) " = NIL ]"))))
    ((eq? (car f) (quote eq?))
      (let ((ra (lval (car (cdr f)) pmap b live)))
        (let ((rb (lval (car (cdr (cdr f))) pmap (car ra) live)))
          (cons (car rb) (str "[ " (dq) (shval (cdr ra)) (dq) " = " (dq) (shval (cdr rb)) (dq) " ]")))))
    ((eq? (car f) (quote pair?))   (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (tagtest   (cdr ra) "P:"))))
    ((eq? (car f) (quote atom?))   (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (natagtest (cdr ra) "P:"))))
    ((eq? (car f) (quote number?)) (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (tagtest   (cdr ra) "I:"))))
    ((eq? (car f) (quote string?)) (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (tagtest   (cdr ra) "T:"))))
    ((eq? (car f) (quote symbol?)) (let ((ra (lval (car (cdr f)) pmap b live))) (cons (car ra) (tagtest   (cdr ra) "S:"))))
    (t (let ((ra (lval (car (cdr f)) pmap b live)))
         (let ((rb (lval (car (cdr (cdr f))) pmap (car ra) live)))
           (cons (car rb) (str "[ " (shdet (cdr ra)) " " (shcmp (car f)) " " (shdet (cdr rb)) " ]"))))))
    ;; non-predicate test (bare var, general call, inlined if): eval -> truthiness
    (let ((rx (lval f pmap b live)))
      (cons (car rx) (str "[ " (dq) (shval (cdr rx)) (dq) " != NIL ]"))))))

;; ltail: TAIL position -> b (each path terminates)
(define ltail (lambda (f pmap fname np b live)
  (cond
    ((if (pair? f) (eq? (car f) (quote if)) nil)
      (let ((ct (ctest (car (cdr f)) pmap b live)))
        (let ((aid (b-npc (car ct))))
          (let ((bid (+ aid 1)))
            (let ((b3 (emit (emit (bnpc+ (bnpc+ (car ct))) (str "if " (cdr ct) "; then PC=" (number->string aid) "; else PC=" (number->string bid) "; fi")) "ACTION=jump; return")))
              (let ((ba (ltail (car (cdr (cdr f))) pmap fname np (switch b3 aid) live)))
                (ltail (cadddr f) pmap fname np (switch ba bid) live)))))))
    ((if (pair? f) (eq? (car f) (quote cond)) nil) (ltail (cond->if (cdr f)) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote and)) nil) (ltail (dsg-and (cdr f)) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote or)) nil) (ltail (dsg-or (cdr f)) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote str)) nil) (ltail (dsg-str (cdr f)) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote list)) nil) (ltail (dsg-list (cdr f)) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote begin)) nil) (ltbegin (cdr f) pmap fname np b live))
    ((if (pair? f) (eq? (car f) (quote let)) nil) (let ((r (lbinds (car (cdr f)) pmap b live))) (ltail (car (cdr (cdr f))) (car (cdr r)) fname np (car r) (car (cdr (cdr r))))))
    ((if (pair? f) (eq? (car f) fname) nil)
      (let ((ar (largs (cdr f) pmap b live)))
        (emit (setparams (car ar) (cdr ar) 0) "PC=0; ACTION=tail; return")))
    (t (let ((r (lval f pmap b live)))
         (emit (car r) (str "R=" (dq) (shval (cdr r)) (dq) "; ACTION=ret; return")))))))

;; assembly
(define pmap-fr (lambda (fs i) (if (null? fs) nil (cons (cons (car fs) (str "p" (number->string i))) (pmap-fr (cdr fs) (+ i 1))))))
(define ploads (lambda (fs i) (if (null? fs) nil (cons (str "eval " (dq) "p" (number->string i) "=" EQT "\$F$((FP+" (number->string i) "))" EQT (dq)) (ploads (cdr fs) (+ i 1))))))
(define blkget (lambda (al pc) (if (null? al) nil (if (eq? (car (car al)) pc) (cdr (car al)) (blkget (cdr al) pc)))))
(define caseblocks (lambda (al i n) (if (= i n) nil (append (cons (str (number->string i) ")") (append (blkget al i) (list ";;"))) (caseblocks al (+ i 1) n)))))

(define compile-fn-bb (lambda (name params body)
  (let ((np (lenl params)) (pm (pmap-fr params 0)) (mn (sh-mangle (symbol->string name))))
    (let ((bf (ltail body pm name np (mkb nil nil 0 1 0 0) nil)))
      (let ((blk (cons (cons (b-pc bf) (rev (b-cur bf) nil)) (b-blk bf))) (fsz (+ np (b-smax bf))))
        (append (cons (str "SIZE_" mn "=" (number->string fsz))
                  (cons (str mn "() {")
                    (append (ploads params 0)
                      (cons (str "FTOP=$((FP + SIZE_" mn "))")
                        (cons (str "NP=" (number->string np)) (cons "case $PC in" (caseblocks blk 0 (b-npc bf))))))))
                (list "esac; }")))))))
(define compile-def-sh (lambda (d) (compile-fn-bb (car (cdr d)) (car (cdr (car (cdr (cdr d))))) (car (cdr (cdr (car (cdr (cdr d)))))))))
