# src/prims-aot.sh -- primitive value-wrappers (src/prims.lisp) compiled to native sh by
# comp-sh.sh. GENERATED by tools/build-prims-aot.sh. Embedded in eval/load so value-position
# primitives ((foldr + 0 xs), (map car ps), ...) resolve to C:__p_<op> fns.
SIZE___p_add=2
__p_add() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE___p_add))
NP=2
case $PC in
0)
sht0="I:$(( ${p0#??} + ${p1#??} ))"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_sub=2
__p_sub() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE___p_sub))
NP=2
case $PC in
0)
sht0="I:$(( ${p0#??} - ${p1#??} ))"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_mul=2
__p_mul() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE___p_mul))
NP=2
case $PC in
0)
sht0="I:$(( ${p0#??} * ${p1#??} ))"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_lt=2
__p_lt() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE___p_lt))
NP=2
case $PC in
0)
if [ ${p0#??} -lt ${p1#??} ]; then
sht0="S:t"
else
sht0="NIL"
fi
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_le=2
__p_le() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE___p_le))
NP=2
case $PC in
0)
if [ ${p0#??} -le ${p1#??} ]; then
sht0="S:t"
else
sht0="NIL"
fi
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_neq=2
__p_neq() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE___p_neq))
NP=2
case $PC in
0)
if [ ${p0#??} -eq ${p1#??} ]; then
sht0="S:t"
else
sht0="NIL"
fi
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_cons=2
__p_cons() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE___p_cons))
NP=2
case $PC in
0)
hp_cons "${p0}" "${p1}"
sht0="${R}"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_car=1
__p_car() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE___p_car))
NP=1
case $PC in
0)
hp_car "${p0}"
sht0="${R}"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_cdr=1
__p_cdr() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE___p_cdr))
NP=1
case $PC in
0)
hp_cdr "${p0}"
sht0="${R}"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_null=1
__p_null() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE___p_null))
NP=1
case $PC in
0)
if [ "${p0}" = NIL ]; then
sht0="S:t"
else
sht0="NIL"
fi
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_eq=2
__p_eq() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE___p_eq))
NP=2
case $PC in
0)
if [ "${p0}" = "${p1}" ]; then
sht0="S:t"
else
sht0="NIL"
fi
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_pair=1
__p_pair() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE___p_pair))
NP=1
case $PC in
0)
if [ "${p0#P:}" != "${p0}" ]; then
sht0="S:t"
else
sht0="NIL"
fi
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE___p_not=1
__p_not() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE___p_not))
NP=1
case $PC in
0)
NFP=$FTOP
eval "F$((NFP+0))=\"\${p0}\""
ARGC=1
CALLEE=not
RPC=1; ACTION=call; return
;;
1)
sht0="${R}"
R="${sht0}"; ACTION=ret; return
;;
esac; }
