# src/stdlib-aot.sh -- AOT-compiled applicative stdlib (native sh), GENERATED by
# tools/build-stdlib-aot.sh from src/stdlib.lisp via comp-sh.sh. Embedded in the eval/load runtimes.
SIZE_not=1
not() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_not))
NP=1
case $PC in
0)
if [ "${p0}" != NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="NIL"; ACTION=ret; return
;;
2)
R="S:t"; ACTION=ret; return
;;
esac; }
SIZE_cadr=1
cadr() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_cadr))
NP=1
case $PC in
0)
hp_cdr "${p0}"
sht0="${R}"
hp_car "${sht0}"
sht1="${R}"
R="${sht1}"; ACTION=ret; return
;;
esac; }
SIZE_caddr=1
caddr() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_caddr))
NP=1
case $PC in
0)
hp_cdr "${p0}"
sht0="${R}"
hp_cdr "${sht0}"
sht1="${R}"
hp_car "${sht1}"
sht2="${R}"
R="${sht2}"; ACTION=ret; return
;;
esac; }
SIZE_cddr=1
cddr() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_cddr))
NP=1
case $PC in
0)
hp_cdr "${p0}"
sht0="${R}"
hp_cdr "${sht0}"
sht1="${R}"
R="${sht1}"; ACTION=ret; return
;;
esac; }
SIZE_cdar=1
cdar() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_cdar))
NP=1
case $PC in
0)
hp_car "${p0}"
sht0="${R}"
hp_cdr "${sht0}"
sht1="${R}"
R="${sht1}"; ACTION=ret; return
;;
esac; }
SIZE_caar=1
caar() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_caar))
NP=1
case $PC in
0)
hp_car "${p0}"
sht0="${R}"
hp_car "${sht0}"
sht1="${R}"
R="${sht1}"; ACTION=ret; return
;;
esac; }
SIZE_cadar=1
cadar() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_cadar))
NP=1
case $PC in
0)
hp_car "${p0}"
sht0="${R}"
hp_cdr "${sht0}"
sht1="${R}"
hp_car "${sht1}"
sht2="${R}"
R="${sht2}"; ACTION=ret; return
;;
esac; }
SIZE_last=1
last() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_last))
NP=1
case $PC in
0)
hp_cdr "${p0}"
sht0="${R}"
if [ "${sht0}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
hp_car "${p0}"
sht1="${R}"
R="${sht1}"; ACTION=ret; return
;;
2)
hp_cdr "${p0}"
sht2="${R}"
eval "F$((FP+0))=\"\${sht2}\""
ARGC=1
PC=0; ACTION=tail; return
;;
esac; }
SIZE_begin=1
begin() {
if [ "$PC" = 0 ]; then
_vi=$ARGC; _vl=NIL
while [ "$_vi" -gt 0 ]; do _vi=$((_vi-1)); eval "_vv=\"\$F$((FP+_vi))\""; hp_cons "$_vv" "$_vl"; _vl=$R; done
eval "F$FP=\"\$_vl\""
fi
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_begin))
NP=1
case $PC in
0)
NFP=$FTOP
eval "F$((NFP+0))=\"\${p0}\""
ARGC=1
CALLEE=last
RPC=1; ACTION=call; return
;;
1)
sht0="${R}"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE_length=1
length() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_length))
NP=1
case $PC in
0)
if [ "${p0}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="I:0"; ACTION=ret; return
;;
2)
hp_cdr "${p0}"
sht0="${R}"
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht0}\""
ARGC=1
CALLEE=length
RPC=3; ACTION=call; return
;;
3)
sht1="${R}"
sht2="I:$(( 1 + ${sht1#??} ))"
R="${sht2}"; ACTION=ret; return
;;
esac; }
SIZE_append=3
append() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_append))
NP=2
case $PC in
0)
if [ "${p0}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="${p1}"; ACTION=ret; return
;;
2)
hp_car "${p0}"
sht0="${R}"
hp_cdr "${p0}"
sht1="${R}"
eval "F$((FP+NP+0))=\"\${sht0}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht1}\""
eval "F$((NFP+1))=\"\${p1}\""
ARGC=2
CALLEE=append
RPC=3; ACTION=call; return
;;
3)
eval "sht0=\"\$F$((FP+NP+0))\""
sht2="${R}"
hp_cons "${sht0}" "${sht2}"
sht3="${R}"
R="${sht3}"; ACTION=ret; return
;;
esac; }
SIZE_reverse=2
reverse() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_reverse))
NP=1
case $PC in
0)
if [ "${p0}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="NIL"; ACTION=ret; return
;;
2)
hp_cdr "${p0}"
sht0="${R}"
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht0}\""
ARGC=1
CALLEE=reverse
RPC=3; ACTION=call; return
;;
3)
sht1="${R}"
hp_car "${p0}"
sht2="${R}"
eval "F$((FP+NP+0))=\"\${sht1}\""
hp_cons "${sht2}" "NIL"
eval "sht1=\"\$F$((FP+NP+0))\""
sht3="${R}"
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht1}\""
eval "F$((NFP+1))=\"\${sht3}\""
ARGC=2
CALLEE=append
RPC=4; ACTION=call; return
;;
4)
sht4="${R}"
R="${sht4}"; ACTION=ret; return
;;
esac; }
SIZE_list_tail=2
list_tail() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_list_tail))
NP=2
case $PC in
0)
if [ ${p1#??} -eq 0 ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="${p0}"; ACTION=ret; return
;;
2)
hp_cdr "${p0}"
sht0="${R}"
sht1="I:$(( ${p1#??} - 1 ))"
eval "F$((FP+0))=\"\${sht0}\""
eval "F$((FP+1))=\"\${sht1}\""
ARGC=2
PC=0; ACTION=tail; return
;;
esac; }
SIZE_nth=2
nth() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_nth))
NP=2
case $PC in
0)
NFP=$FTOP
eval "F$((NFP+0))=\"\${p0}\""
eval "F$((NFP+1))=\"\${p1}\""
ARGC=2
CALLEE=list_tail
RPC=1; ACTION=call; return
;;
1)
sht0="${R}"
hp_car "${sht0}"
sht1="${R}"
R="${sht1}"; ACTION=ret; return
;;
esac; }
SIZE_take=3
take() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_take))
NP=2
case $PC in
0)
if [ ${p1#??} -eq 0 ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="NIL"; ACTION=ret; return
;;
2)
if [ "${p0}" = NIL ]; then PC=3; else PC=4; fi
ACTION=jump; return
;;
3)
R="NIL"; ACTION=ret; return
;;
4)
hp_car "${p0}"
sht0="${R}"
hp_cdr "${p0}"
sht1="${R}"
sht2="I:$(( ${p1#??} - 1 ))"
eval "F$((FP+NP+0))=\"\${sht0}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht1}\""
eval "F$((NFP+1))=\"\${sht2}\""
ARGC=2
CALLEE=take
RPC=5; ACTION=call; return
;;
5)
eval "sht0=\"\$F$((FP+NP+0))\""
sht3="${R}"
hp_cons "${sht0}" "${sht3}"
sht4="${R}"
R="${sht4}"; ACTION=ret; return
;;
esac; }
SIZE_drop=2
drop() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_drop))
NP=2
case $PC in
0)
NFP=$FTOP
eval "F$((NFP+0))=\"\${p0}\""
eval "F$((NFP+1))=\"\${p1}\""
ARGC=2
CALLEE=list_tail
RPC=1; ACTION=call; return
;;
1)
sht0="${R}"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE_memberzzQ=2
memberzzQ() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_memberzzQ))
NP=2
case $PC in
0)
if [ "${p1}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="NIL"; ACTION=ret; return
;;
2)
hp_car "${p1}"
sht0="${R}"
if [ "${p0}" = "${sht0}" ]; then PC=3; else PC=4; fi
ACTION=jump; return
;;
3)
R="S:t"; ACTION=ret; return
;;
4)
hp_cdr "${p1}"
sht1="${R}"
eval "F$((FP+0))=\"\${p0}\""
eval "F$((FP+1))=\"\${sht1}\""
ARGC=2
PC=0; ACTION=tail; return
;;
esac; }
SIZE_assoc=2
assoc() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_assoc))
NP=2
case $PC in
0)
if [ "${p1}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="NIL"; ACTION=ret; return
;;
2)
NFP=$FTOP
eval "F$((NFP+0))=\"\${p1}\""
ARGC=1
CALLEE=caar
RPC=3; ACTION=call; return
;;
3)
sht0="${R}"
if [ "${p0}" = "${sht0}" ]; then PC=4; else PC=5; fi
ACTION=jump; return
;;
4)
hp_car "${p1}"
sht1="${R}"
R="${sht1}"; ACTION=ret; return
;;
5)
hp_cdr "${p1}"
sht2="${R}"
eval "F$((FP+0))=\"\${p0}\""
eval "F$((FP+1))=\"\${sht2}\""
ARGC=2
PC=0; ACTION=tail; return
;;
esac; }
SIZE_map=3
map() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_map))
NP=2
case $PC in
0)
if [ "${p1}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="NIL"; ACTION=ret; return
;;
2)
hp_car "${p1}"
sht0="${R}"
eval "F$((FP+NP+0))=\"\${p0}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht0}\""
ARGC=1
CALLEE=${p0}
RPC=3; ACTION=call; return
;;
3)
eval "p0=\"\$F$((FP+NP+0))\""
sht1="${R}"
hp_cdr "${p1}"
sht2="${R}"
eval "F$((FP+NP+0))=\"\${sht1}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${p0}\""
eval "F$((NFP+1))=\"\${sht2}\""
ARGC=2
CALLEE=map
RPC=4; ACTION=call; return
;;
4)
eval "sht1=\"\$F$((FP+NP+0))\""
sht3="${R}"
hp_cons "${sht1}" "${sht3}"
sht4="${R}"
R="${sht4}"; ACTION=ret; return
;;
esac; }
SIZE_map2=4
map2() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
eval "p2=\"\$F$((FP+2))\""
FTOP=$((FP + SIZE_map2))
NP=3
case $PC in
0)
if [ "${p1}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="NIL"; ACTION=ret; return
;;
2)
hp_car "${p1}"
sht0="${R}"
hp_car "${p2}"
sht1="${R}"
eval "F$((FP+NP+0))=\"\${p0}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht0}\""
eval "F$((NFP+1))=\"\${sht1}\""
ARGC=2
CALLEE=${p0}
RPC=3; ACTION=call; return
;;
3)
eval "p0=\"\$F$((FP+NP+0))\""
sht2="${R}"
hp_cdr "${p1}"
sht3="${R}"
hp_cdr "${p2}"
sht4="${R}"
eval "F$((FP+NP+0))=\"\${sht2}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${p0}\""
eval "F$((NFP+1))=\"\${sht3}\""
eval "F$((NFP+2))=\"\${sht4}\""
ARGC=3
CALLEE=map2
RPC=4; ACTION=call; return
;;
4)
eval "sht2=\"\$F$((FP+NP+0))\""
sht5="${R}"
hp_cons "${sht2}" "${sht5}"
sht6="${R}"
R="${sht6}"; ACTION=ret; return
;;
esac; }
SIZE_zip=2
zip() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_zip))
NP=2
case $PC in
0)
hp_cons "S:__sl0" "NIL"
sht0="${R}"
sht1="K:${sht0#P:}"
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht1}\""
eval "F$((NFP+1))=\"\${p0}\""
eval "F$((NFP+2))=\"\${p1}\""
ARGC=3
CALLEE=map2
RPC=1; ACTION=call; return
;;
1)
sht2="${R}"
R="${sht2}"; ACTION=ret; return
;;
esac; }
SIZE___sl0=2
__sl0() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
_clrs=$R
R=$_clrs
FTOP=$((FP + SIZE___sl0))
NP=2
case $PC in
0)
hp_cons "${p0}" "${p1}"
sht0="${R}"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE_filter=3
filter() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_filter))
NP=2
case $PC in
0)
if [ "${p1}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="NIL"; ACTION=ret; return
;;
2)
hp_car "${p1}"
sht0="${R}"
eval "F$((FP+NP+0))=\"\${p0}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht0}\""
ARGC=1
CALLEE=${p0}
RPC=3; ACTION=call; return
;;
3)
eval "p0=\"\$F$((FP+NP+0))\""
sht1="${R}"
if [ "${sht1}" != NIL ]; then PC=4; else PC=5; fi
ACTION=jump; return
;;
4)
hp_car "${p1}"
sht2="${R}"
hp_cdr "${p1}"
sht3="${R}"
eval "F$((FP+NP+0))=\"\${sht2}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${p0}\""
eval "F$((NFP+1))=\"\${sht3}\""
ARGC=2
CALLEE=filter
RPC=6; ACTION=call; return
;;
5)
hp_cdr "${p1}"
sht6="${R}"
eval "F$((FP+0))=\"\${p0}\""
eval "F$((FP+1))=\"\${sht6}\""
ARGC=2
PC=0; ACTION=tail; return
;;
6)
eval "sht2=\"\$F$((FP+NP+0))\""
sht4="${R}"
hp_cons "${sht2}" "${sht4}"
sht5="${R}"
R="${sht5}"; ACTION=ret; return
;;
esac; }
SIZE_foldl=5
foldl() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
eval "p2=\"\$F$((FP+2))\""
FTOP=$((FP + SIZE_foldl))
NP=3
case $PC in
0)
if [ "${p2}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="${p1}"; ACTION=ret; return
;;
2)
hp_car "${p2}"
sht0="${R}"
eval "F$((FP+NP+0))=\"\${p0}\""
eval "F$((FP+NP+1))=\"\${p0}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${p1}\""
eval "F$((NFP+1))=\"\${sht0}\""
ARGC=2
CALLEE=${p0}
RPC=3; ACTION=call; return
;;
3)
eval "p0=\"\$F$((FP+NP+0))\""
eval "p0=\"\$F$((FP+NP+1))\""
sht1="${R}"
hp_cdr "${p2}"
sht2="${R}"
eval "F$((FP+0))=\"\${p0}\""
eval "F$((FP+1))=\"\${sht1}\""
eval "F$((FP+2))=\"\${sht2}\""
ARGC=3
PC=0; ACTION=tail; return
;;
esac; }
SIZE_foldr=5
foldr() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
eval "p2=\"\$F$((FP+2))\""
FTOP=$((FP + SIZE_foldr))
NP=3
case $PC in
0)
if [ "${p2}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="${p1}"; ACTION=ret; return
;;
2)
hp_car "${p2}"
sht0="${R}"
hp_cdr "${p2}"
sht1="${R}"
eval "F$((FP+NP+0))=\"\${sht0}\""
eval "F$((FP+NP+1))=\"\${p0}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${p0}\""
eval "F$((NFP+1))=\"\${p1}\""
eval "F$((NFP+2))=\"\${sht1}\""
ARGC=3
CALLEE=foldr
RPC=3; ACTION=call; return
;;
3)
eval "sht0=\"\$F$((FP+NP+0))\""
eval "p0=\"\$F$((FP+NP+1))\""
sht2="${R}"
eval "F$((FP+NP+0))=\"\${p0}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht0}\""
eval "F$((NFP+1))=\"\${sht2}\""
ARGC=2
CALLEE=${p0}
RPC=4; ACTION=call; return
;;
4)
eval "p0=\"\$F$((FP+NP+0))\""
sht3="${R}"
R="${sht3}"; ACTION=ret; return
;;
esac; }
SIZE_for_each=3
for_each() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_for_each))
NP=2
case $PC in
0)
if [ "${p1}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="NIL"; ACTION=ret; return
;;
2)
hp_car "${p1}"
sht0="${R}"
eval "F$((FP+NP+0))=\"\${p0}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht0}\""
ARGC=1
CALLEE=${p0}
RPC=3; ACTION=call; return
;;
3)
eval "p0=\"\$F$((FP+NP+0))\""
sht1="${R}"
hp_cdr "${p1}"
sht2="${R}"
eval "F$((FP+0))=\"\${p0}\""
eval "F$((FP+1))=\"\${sht2}\""
ARGC=2
PC=0; ACTION=tail; return
;;
esac; }
SIZE_compose=3
compose() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_compose))
NP=2
case $PC in
0)
eval "F$((FP+NP+0))=\"\${p1}\""
hp_cons "${p0}" "NIL"
eval "p1=\"\$F$((FP+NP+0))\""
sht0="${R}"
hp_cons "${p1}" "${sht0}"
sht1="${R}"
hp_cons "S:__sl1" "${sht1}"
sht2="${R}"
sht3="K:${sht2#P:}"
R="${sht3}"; ACTION=ret; return
;;
esac; }
SIZE___sl1=3
__sl1() {
eval "p0=\"\$F$((FP+0))\""
_clrs=$R
hp_cdr "P:${CLO}"
_cl="${R}"
hp_car "${_cl}"
p1="${R}"
hp_cdr "${_cl}"
_cl="${R}"
hp_car "${_cl}"
p2="${R}"
hp_cdr "${_cl}"
_cl="${R}"
R=$_clrs
FTOP=$((FP + SIZE___sl1))
NP=1
case $PC in
0)
eval "F$((FP+NP+0))=\"\${p1}\""
eval "F$((FP+NP+1))=\"\${p2}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${p0}\""
ARGC=1
CALLEE=${p1}
RPC=1; ACTION=call; return
;;
1)
eval "p1=\"\$F$((FP+NP+0))\""
eval "p2=\"\$F$((FP+NP+1))\""
sht0="${R}"
eval "F$((FP+NP+0))=\"\${p2}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht0}\""
ARGC=1
CALLEE=${p2}
RPC=2; ACTION=call; return
;;
2)
eval "p2=\"\$F$((FP+NP+0))\""
sht1="${R}"
R="${sht1}"; ACTION=ret; return
;;
esac; }
SIZE_abs=1
abs() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_abs))
NP=1
case $PC in
0)
if [ ${p0#??} -lt 0 ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
sht0="I:$(( 0 - ${p0#??} ))"
R="${sht0}"; ACTION=ret; return
;;
2)
R="${p0}"; ACTION=ret; return
;;
esac; }
SIZE_max=2
max() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_max))
NP=2
case $PC in
0)
if [ ${p0#??} -lt ${p1#??} ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="${p1}"; ACTION=ret; return
;;
2)
R="${p0}"; ACTION=ret; return
;;
esac; }
SIZE_min=2
min() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_min))
NP=2
case $PC in
0)
if [ ${p0#??} -lt ${p1#??} ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="${p0}"; ACTION=ret; return
;;
2)
R="${p1}"; ACTION=ret; return
;;
esac; }
SIZE_sum=1
sum() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_sum))
NP=1
case $PC in
0)
hp_cons "S:__sl2" "NIL"
sht0="${R}"
sht1="K:${sht0#P:}"
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht1}\""
eval "F$((NFP+1))=\"I:0\""
eval "F$((NFP+2))=\"\${p0}\""
ARGC=3
CALLEE=foldl
RPC=1; ACTION=call; return
;;
1)
sht2="${R}"
R="${sht2}"; ACTION=ret; return
;;
esac; }
SIZE___sl2=2
__sl2() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
_clrs=$R
R=$_clrs
FTOP=$((FP + SIZE___sl2))
NP=2
case $PC in
0)
sht0="I:$(( ${p0#??} + ${p1#??} ))"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE_product=1
product() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_product))
NP=1
case $PC in
0)
hp_cons "S:__sl3" "NIL"
sht0="${R}"
sht1="K:${sht0#P:}"
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht1}\""
eval "F$((NFP+1))=\"I:1\""
eval "F$((NFP+2))=\"\${p0}\""
ARGC=3
CALLEE=foldl
RPC=1; ACTION=call; return
;;
1)
sht2="${R}"
R="${sht2}"; ACTION=ret; return
;;
esac; }
SIZE___sl3=2
__sl3() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
_clrs=$R
R=$_clrs
FTOP=$((FP + SIZE___sl3))
NP=2
case $PC in
0)
sht0="I:$(( ${p0#??} * ${p1#??} ))"
R="${sht0}"; ACTION=ret; return
;;
esac; }
SIZE__zzGstring=1
_zzGstring() {
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE__zzGstring))
NP=1
case $PC in
0)
if [ "${p0#T:}" != "${p0}" ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="${p0}"; ACTION=ret; return
;;
2)
if [ "${p0#I:}" != "${p0}" ]; then PC=3; else PC=4; fi
ACTION=jump; return
;;
3)
sht0="T:${p0#??}"
R="${sht0}"; ACTION=ret; return
;;
4)
if [ "${p0#S:}" != "${p0}" ]; then PC=5; else PC=6; fi
ACTION=jump; return
;;
5)
sht1="T:${p0#??}"
R="${sht1}"; ACTION=ret; return
;;
6)
R="${p0}"; ACTION=ret; return
;;
esac; }
SIZE_str=1
str() {
if [ "$PC" = 0 ]; then
_vi=$ARGC; _vl=NIL
while [ "$_vi" -gt 0 ]; do _vi=$((_vi-1)); eval "_vv=\"\$F$((FP+_vi))\""; hp_cons "$_vv" "$_vl"; _vl=$R; done
eval "F$FP=\"\$_vl\""
fi
eval "p0=\"\$F$((FP+0))\""
FTOP=$((FP + SIZE_str))
NP=1
case $PC in
0)
hp_cons "S:__sl4" "NIL"
sht0="${R}"
sht1="K:${sht0#P:}"
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht1}\""
STGV="T:"
eval "F$((NFP+1))=\"\$STGV\""
eval "F$((NFP+2))=\"\${p0}\""
ARGC=3
CALLEE=foldl
RPC=1; ACTION=call; return
;;
1)
sht2="${R}"
R="${sht2}"; ACTION=ret; return
;;
esac; }
SIZE___sl4=3
__sl4() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
_clrs=$R
R=$_clrs
FTOP=$((FP + SIZE___sl4))
NP=2
case $PC in
0)
eval "F$((FP+NP+0))=\"\${p0}\""
NFP=$FTOP
eval "F$((NFP+0))=\"\${p1}\""
ARGC=1
CALLEE=_zzGstring
RPC=1; ACTION=call; return
;;
1)
eval "p0=\"\$F$((FP+NP+0))\""
sht0="${R}"
sht1="T:${p0#??}${sht0#??}"
R="${sht1}"; ACTION=ret; return
;;
esac; }
SIZE_join=2
join() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
FTOP=$((FP + SIZE_join))
NP=2
case $PC in
0)
if [ "${p1}" = NIL ]; then PC=1; else PC=2; fi
ACTION=jump; return
;;
1)
R="T:"; ACTION=ret; return
;;
2)
hp_cons "${p0}" "NIL"
sht0="${R}"
hp_cons "S:__sl5" "${sht0}"
sht1="${R}"
sht2="K:${sht1#P:}"
hp_car "${p1}"
sht3="${R}"
hp_cdr "${p1}"
sht4="${R}"
NFP=$FTOP
eval "F$((NFP+0))=\"\${sht2}\""
eval "F$((NFP+1))=\"\${sht3}\""
eval "F$((NFP+2))=\"\${sht4}\""
ARGC=3
CALLEE=foldl
RPC=3; ACTION=call; return
;;
3)
sht5="${R}"
R="${sht5}"; ACTION=ret; return
;;
esac; }
SIZE___sl5=2
__sl5() {
eval "p0=\"\$F$((FP+0))\""
eval "p1=\"\$F$((FP+1))\""
_clrs=$R
hp_cdr "P:${CLO}"
_cl="${R}"
hp_car "${_cl}"
p2="${R}"
hp_cdr "${_cl}"
_cl="${R}"
R=$_clrs
FTOP=$((FP + SIZE___sl5))
NP=2
case $PC in
0)
sht0="T:${p2#??}${p1#??}"
sht1="T:${p0#??}${sht0#??}"
R="${sht1}"; ACTION=ret; return
;;
esac; }
# G_ registrations: stdlib fns as first-class globals (cross-unit value/operator refs)
G_not="C:not"
G_cadr="C:cadr"
G_caddr="C:caddr"
G_cddr="C:cddr"
G_cdar="C:cdar"
G_caar="C:caar"
G_cadar="C:cadar"
G_last="C:last"
G_begin="C:begin"
G_length="C:length"
G_append="C:append"
G_reverse="C:reverse"
G_list_tail="C:list_tail"
G_nth="C:nth"
G_take="C:take"
G_drop="C:drop"
G_memberzzQ="C:memberzzQ"
G_assoc="C:assoc"
G_map="C:map"
G_map2="C:map2"
G_zip="C:zip"
G_filter="C:filter"
G_foldl="C:foldl"
G_foldr="C:foldr"
G_for_each="C:for_each"
G_compose="C:compose"
G_abs="C:abs"
G_max="C:max"
G_min="C:min"
G_sum="C:sum"
G_product="C:product"
G__zzGstring="C:_zzGstring"
G_str="C:str"
G_join="C:join"
